"""reviewer-1: independent re-derivation of the orbit CNF for a (5,5)-good graph
on n vertices admitting the permutation sigma of cycle type 1^f p^k, written
without reference to encode.py / verify.py beyond the published *conventions*
(vertex layout, variable numbering by least pair, clause = one per 5-set and
colour).  Also an independent implementation of the redundant constraints
D / C / T / P of hybrid.py using a *sequential-counter free* approach: we do not
try to match the auxiliary clauses literally; instead we check the base clause
set for equality and check the redundant part semantically (see audit_hybrid).

usage: python3 indep_encode.py n f p k            -> prints stats
"""
import sys
from itertools import combinations


def permutation(n, f, p, k):
    assert f + p * k == n
    sig = list(range(n))
    for j in range(k):
        for i in range(p):
            sig[f + j * p + i] = f + j * p + (i + 1) % p
    return sig


def orbits_of_pairs(n, sig):
    """Orbits of unordered pairs under the cyclic group generated by sig.
    Returns (var, nvars) with var[(u,v)] (u<v) = 1-based orbit index, orbits
    numbered by their lexicographically least member."""
    # order of sig
    order = 1
    cur = sig[:]
    ident = list(range(n))
    while cur != ident:
        cur = [sig[x] for x in cur]
        order += 1
    powers = [ident]
    for _ in range(order - 1):
        powers.append([sig[x] for x in powers[-1]])
    var = {}
    nv = 0
    for u, v in combinations(range(n), 2):
        if (u, v) in var:
            continue
        nv += 1
        for g in powers:
            a, b = g[u], g[v]
            key = (a, b) if a < b else (b, a)
            assert var.get(key, nv) == nv
            var[key] = nv
    return var, nv


def base_clauses(n, var):
    """Set of clauses (as frozensets of literals) forbidding K5 / I5 on every
    5-set, with duplicates collapsed."""
    cl = set()
    for S in combinations(range(n), 5):
        m = {var[e] for e in combinations(S, 2)}
        cl.add(frozenset(-x for x in m))
        cl.add(frozenset(m))
    return cl


if __name__ == '__main__':
    n, f, p, k = map(int, sys.argv[1:5])
    sig = permutation(n, f, p, k)
    var, nv = orbits_of_pairs(n, sig)
    cl = base_clauses(n, var)
    print(f"1^{f} {p}^{k}: {nv} orbit variables, {len(cl)} distinct base clauses")
