"""reviewer-1: independent recount of the class numbers quoted by h2873
("Z_3-good graphs on 1/2/3/4 cycles: 1/5/47/1576 classes"): enumerate all good
labelled Z_3-prefixes on m cycles and partition them into orbits of the group
generated by cube_check.vertex_maps (S_m on cycles, rotation of each cycle,
i -> 2i, complementation).

usage: python3 level_counts.py MAXLEVEL
"""
import sys
from itertools import combinations
import cube_check as CC


def enumerate_good(kk, p=3):
    nbits = kk + 3 * (kk * (kk - 1) // 2)
    out = set()

    def dfs(a, obj):
        if a == kk:
            out.add(obj)
            return
        for code in range(2):
            for wbits in range(1 << (3 * a)):
                o = obj | (code << a)
                if a:
                    o |= wbits << CC.pair_index(0, a, kk)
                adj = partial_adj(o, a + 1, kk, p)
                if CC.good(adj, p * (a + 1)):
                    dfs(a + 1, o)

    def partial_adj(obj, m, kk, p):
        nvp = p * m
        adj = [0] * nvp
        v = lambda a, i: p * a + i % p
        for a in range(m):
            if obj >> a & 1:
                for i, j in combinations(range(p), 2):
                    adj[v(a, i)] |= 1 << v(a, j)
                    adj[v(a, j)] |= 1 << v(a, i)
        for a, b in combinations(range(m), 2):
            off = CC.pair_index(a, b, kk)
            for r in range(p):
                if obj >> (off + r) & 1:
                    for i in range(p):
                        adj[v(a, i)] |= 1 << v(b, i + r)
                        adj[v(b, i + r)] |= 1 << v(a, i)
        return adj

    dfs(0, 0)
    return out, nbits


def main():
    maxlevel = int(sys.argv[1])
    for kk in range(1, maxlevel + 1):
        goods, nbits = enumerate_good(kk)
        acts = []
        for perm, comp in CC.vertex_maps(kk):
            table, xor = CC.bit_action(perm, comp, kk, nbits)
            acts.append(CC.make_apply(table, xor, nbits))
        seen = set()
        orbits = 0
        for g in goods:
            if g in seen:
                continue
            orbits += 1
            stack = [g]
            seen.add(g)
            while stack:
                o = stack.pop()
                for a in acts:
                    q = a(o)
                    if q not in seen:
                        seen.add(q)
                        stack.append(q)
        assert seen == goods, 'an orbit left the good set'
        print(f'level {kk}: {len(goods)} good labelled prefixes of {2 ** kk * 8 ** (kk * (kk - 1) // 2)}, '
              f'{orbits} classes')


if __name__ == '__main__':
    main()
