"""The order-8 row, sized: how many actions survive the orbit bound.

researcher-1, `r55-42-automorphism-census`: *"order 8 is no better, which kills
the obvious escape. Excluding every group of order 8 would bound the Sylow
2-subgroup by 4 and so bound a -- which nothing does today"*, and it measured
**one** Z_2^3 action (five regular orbits and one of size 2, 126 pair orbits,
15 of 15 cubes timing out).

That is a probe, not an enumeration.  This file does the enumeration, which is
this seat's job: for each of the five groups of order 8, every faithful action
on 42 points, filtered by the orbit lemma.

WHAT THE ORBIT LEMMA GIVES HERE.  For any orbit O of H,

    |Fix(H)| <= R(5-w,5) - 1 + R(5,5-a) - 1,   w, a the clique and
                                               independence numbers of F[O],

maximised over the H-invariant graphs on O that can occur in a (5,5)-graph.
Evaluated per orbit size and per induced group:

    orbit size 2                     37
    orbit size 4 (cyclic or Klein)   26, and 22 after the global count
    orbit size 8, cyclic             17
    orbit size 8, Z_2^3 regular      13

so the bound depends on *which* group acts on the orbit, not only on its size.
An action is kept only if its fixed-point count respects the minimum over all
its orbits.

    python3 order8.py
"""
import itertools
import os
import sys
import time
from collections import Counter

CAP = 240  # seconds per group; Z_2^3 is the one that overruns

import orbitbound as OB

# The five groups of order 8, as multiplication tables on {0..7} with 0 the
# identity.  Built from explicit permutation representations so the tables are
# derived rather than typed in.
def _closure(gens, n):
    """The permutation group generated by `gens`, as a sorted list."""
    seen, frontier = set(), [tuple(range(n))]
    while frontier:
        x = frontier.pop()
        if x in seen:
            continue
        seen.add(x)
        for g in gens:
            frontier.append(tuple(g[x[i]] for i in range(n)))
    return sorted(seen)


def groups_of_order_8():
    """(name, elements as permutations) for each of the five groups."""
    out = []
    # Z_8: an 8-cycle
    out.append(("Z_8", _closure([tuple((i + 1) % 8 for i in range(8))], 8)))
    # Z_4 x Z_2: a 4-cycle and a disjoint transposition, on 6 points
    g1 = (1, 2, 3, 0, 4, 5)
    g2 = (0, 1, 2, 3, 5, 4)
    out.append(("Z_4 x Z_2", _closure([g1, g2], 6)))
    # Z_2^3: three disjoint transpositions
    e = []
    for i in range(3):
        p = list(range(6))
        p[2 * i], p[2 * i + 1] = 2 * i + 1, 2 * i
        e.append(tuple(p))
    out.append(("Z_2^3", _closure(e, 6)))
    # D_4: symmetries of a square
    r = (1, 2, 3, 0)
    s = (1, 0, 3, 2)
    out.append(("D_4", _closure([r, s], 4)))
    # Q_8: the quaternions, as a regular permutation group built from the
    # presentation i^4 = 1, j^2 = i^2, j i j^-1 = i^-1
    idx = {}
    els = []
    for a in range(4):
        for b in range(2):
            idx[(a, b)] = len(els)
            els.append((a, b))

    def mul(x, y):
        a, b = els[x]
        c, d = els[y]
        # (i^a j^b)(i^c j^d) = i^(a + (-1)^b c + 2bd) j^(b+d mod 2)
        na = (a + (c if b == 0 else -c) + 2 * b * d) % 4
        nb = (b + d) % 2
        return idx[(na, nb)]
    perms = []
    for x in range(8):
        perms.append(tuple(mul(x, y) for y in range(8)))
    out.append(("Q_8", sorted(perms)))
    return out


def table(els):
    """Multiplication table with 0 the identity."""
    n = len(els[0])
    ident = tuple(range(n))
    order = [els.index(ident)] + [i for i in range(8) if els[i] != ident]
    pos = {els[order[k]]: k for k in range(8)}
    tab = [[0] * 8 for _ in range(8)]
    for i in range(8):
        a = els[order[i]]
        for j in range(8):
            b = els[order[j]]
            tab[i][j] = pos[tuple(a[b[k]] for k in range(n))]
    return tab


def subgroups(tab):
    out = []
    for size in (1, 2, 4, 8):
        for S in itertools.combinations(range(8), size):
            s = set(S)
            if 0 not in s:
                continue
            if all(tab[a][b] in s for a in s for b in s):
                out.append(frozenset(s))
    return out


def coset_action(tab, H):
    """G acting on the left cosets of H; returns (m, generators)."""
    cos = []
    seen = set()
    for g in range(8):
        c = frozenset(tab[g][h] for h in H)
        if c not in seen:
            seen.add(c)
            cos.append(c)
    idx = {c: i for i, c in enumerate(cos)}
    perms = []
    for g in range(8):
        p = []
        for c in cos:
            gc = frozenset(tab[g][x] for x in c)
            p.append(idx[gc])
        perms.append(tuple(p))
    return len(cos), perms


def orbit_cap(tab, H):
    """The best bound this lane has for an orbit with stabiliser H.

    The orbit lemma alone gives R(5-w,5)-1 + R(5,5-a)-1 maximised over the
    admissible shapes.  At orbit size 4 that is 26 -- but FIXED-POINT-MAXIMUM.md
    proves 22 at n = 42 for ANY subgroup possessing a 4-orbit, by refuting the
    26-, 25- and 24-point configurations.  The first version of this file used
    26 and so failed to apply this lane's own strongest result to the new row,
    which is precisely the error I diagnosed in researcher-1's lane at pass 53.
    """
    m, perms = coset_action(tab, H)
    if m == 1:
        return None                      # a fixed point constrains nothing
    b, _, _ = OB.orbit_bound(perms, m, 5, 5)
    if m == 4:
        b = min(b, 22)                   # the global count at n = 42
    return b


def automorphisms_of(tab):
    """Aut(G) by brute force over bijections fixing the identity.

    Needed because an action is a multiset of point stabilisers, and two
    multisets related by an automorphism of G give isomorphic actions -- the
    same distinction as ordered 6465 versus unordered 1347 in the Klein case.
    """
    out = []
    for p in itertools.permutations(range(1, 8)):
        m = (0,) + p
        if all(m[tab[a][b]] == tab[m[a]][m[b]] for a in range(8)
               for b in range(8)):
            out.append(m)
    return out


def canon(counts, subs, auts):
    """Canonical form of a stabiliser multiset under Aut(G)."""
    best = None
    for m in auts:
        img = {}
        for H, c in counts.items():
            if c:
                img[frozenset(m[x] for x in H)] = c
        key = tuple(sorted((tuple(sorted(H)), c) for H, c in img.items()))
        best = key if best is None else min(best, key)
    return best


def main():
    print("THE ORDER-8 ROW, SIZED\n")
    print("   For each group of order 8: every faithful action on 42 points,")
    print("   with the orbit lemma applied per orbit.  researcher-1 probed one")
    print("   Z_2^3 action; this is the enumeration.\n")
    print("   group        subgroups   per-orbit caps            actions   "
          "max |Fix|")
    total = 0
    for name, els in groups_of_order_8():
        tab = table(els)
        subs = subgroups(tab)
        caps = {}
        for H in subs:
            caps[H] = orbit_cap(tab, H)
        capstr = ", ".join(
            f"{8 // len(H)}:{caps[H]}" for H in
            sorted(subs, key=lambda h: -len(h)) if caps[H] is not None)
        # enumerate multisets of stabilisers with total index 42
        auts = automorphisms_of(tab)
        seen, best, raw = set(), -1, 0
        t0 = time.time()
        timed_out = [False]

        def rec(i, left, chosen):
            nonlocal best, raw
            if timed_out[0]:
                return
            if time.time() - t0 > CAP:
                timed_out[0] = True
                return
            if left == 0:
                # faithfulness: the intersection of the cores is trivial.
                # For these groups every subgroup is normal except in D_4 and
                # Q_8, where the core of a non-normal subgroup is computed by
                # intersecting conjugates; taking the plain intersection of the
                # chosen stabilisers is correct for normal ones and a valid
                # over-approximation otherwise, so the count is an upper bound
                # in those two cases and exact for the three abelian groups.
                inter = set(range(8))
                for H, c in chosen:
                    if c:
                        inter &= set(H)
                if len(inter) != 1:
                    return
                f = sum(c for H, c in chosen if len(H) == 8)
                cap = min((caps[H] for H, c in chosen
                           if c and caps[H] is not None), default=42)
                if f > cap:
                    return
                raw += 1
                seen.add(canon({H: c for H, c in chosen}, subs, auts))
                best = max(best, f)
                return
            if i == len(order_subs):
                return
            H = order_subs[i]
            idx = 8 // len(H)
            for c in range(left // idx + 1):
                rec(i + 1, left - c * idx, chosen + [(H, c)])

        order_subs = sorted(subs, key=lambda h: -len(h))
        rec(0, 42, [])
        mark = "  (incomplete, capped)" if timed_out[0] else ""
        total += len(seen)
        print(f"   {name:12s} {len(subs):5d}  {capstr:46s}")
        print(f"       ordered {raw:8d}   up to Aut(G) {len(seen):8d}   "
              f"max |Fix| {best:3d}{mark}", flush=True)
    print(f"\n   total faithful actions surviving the orbit lemma: {total}")
    print("\n   Exact for the three abelian groups; an upper bound for D_4 and")
    print("   Q_8, where faithfulness is tested by intersecting the chosen")
    print("   stabilisers rather than their cores.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
