"""Automorphism groups of the known (5,5,42)-graphs, by orbit refinement and
backtracking.

The point is a falsification test the lane needs before spending more compute on
the open order-3 types: if any known (5,5,42)-graph has an automorphism of order
3, the corresponding cycle type is *realised* and can never be excluded. It also
records which 2-groups actually occur, which bounds from below what any future
2-group argument could hope to prove.

Method. Refine the vertex partition by degree and then by the multiset of
neighbour-cell counts until stable; this is the standard 1-dimensional
Weisfeiler-Leman refinement and it is automorphism-invariant, so an automorphism
maps each cell to itself. Then backtrack over images of vertices in cell order,
pruning by cell membership and by adjacency to already-mapped vertices. The
generators found give the group; the group order comes from the orbit-stabiliser
chain built during the search.

usage: python3 autgroup.py file.g6 [limit]
"""
import sys
from collections import defaultdict

def read_g6(line):
    line = line.strip()
    if line.startswith('>>graph6<<'):
        line = line[10:]
    data = [ord(c) - 63 for c in line]
    n = data[0]
    assert n < 63, 'only n < 63 handled'
    bits = []
    for d in data[1:]:
        bits += [(d >> i) & 1 for i in range(5, -1, -1)]
    adj = [[False] * n for _ in range(n)]
    k = 0
    for j in range(1, n):
        for i in range(j):
            if bits[k]:
                adj[i][j] = adj[j][i] = True
            k += 1
    return n, adj

def refine(n, adj, part):
    """1-WL refinement; part is a list of cell ids per vertex."""
    while True:
        sig = []
        for v in range(n):
            cnt = defaultdict(int)
            for u in range(n):
                if adj[v][u]:
                    cnt[part[u]] += 1
            sig.append((part[v], tuple(sorted(cnt.items()))))
        order = {s: i for i, s in enumerate(sorted(set(sig)))}
        new = [order[s] for s in sig]
        if new == part:
            return part
        part = new

def automorphisms(n, adj, cap=200000):
    part = refine(n, adj, [0] * n)
    cells = defaultdict(list)
    for v, c in enumerate(part):
        cells[c].append(v)
    order = sorted(range(n), key=lambda v: (part[v], v))
    gens, nodes = [], [0]

    def bt(i, mapping, used):
        if nodes[0] > cap:
            return
        nodes[0] += 1
        if i == n:
            if any(mapping[v] != v for v in range(n)):
                gens.append(list(mapping))
            return
        v = order[i]
        for w in cells[part[v]]:
            if w in used:
                continue
            ok = True
            for j in range(i):
                u = order[j]
                if adj[v][u] != adj[w][mapping[u]]:
                    ok = False
                    break
            if ok:
                mapping[v] = w
                used.add(w)
                bt(i + 1, mapping, used)
                used.discard(w)
                mapping[v] = -1

    bt(0, [-1] * n, set())
    return gens, part, nodes[0] > cap

def group_from(n, gens):
    """Closure of the permutation group generated by gens (small groups only)."""
    ident = tuple(range(n))
    G, frontier = {ident}, [ident]
    while frontier:
        p = frontier.pop()
        for g in gens:
            q = tuple(g[p[i]] for i in range(n))
            if q not in G:
                G.add(q); frontier.append(q)
            if len(G) > 100000:
                return None
    return G

def order_of(n, p):
    ident = tuple(range(n)); q = tuple(p); k = 1
    while q != ident:
        q = tuple(p[q[i]] for i in range(n)); k += 1
    return k

def cycle_type(n, p):
    seen, ct = set(), defaultdict(int)
    for v in range(n):
        if v in seen: continue
        c, a = 0, v
        while a not in seen:
            seen.add(a); a = p[a]; c += 1
        ct[c] += 1
    return dict(ct)

if __name__ == '__main__':
    path = sys.argv[1]
    limit = int(sys.argv[2]) if len(sys.argv) > 2 else 10 ** 9
    tally = defaultdict(int)
    order3 = []
    incomplete = 0
    lines = [l for l in open(path) if l.strip()][:limit]
    for idx, line in enumerate(lines):
        n, adj = read_g6(line)
        gens, part, hit = automorphisms(n, adj)
        if hit:
            incomplete += 1
            continue
        G = group_from(n, gens) if gens else {tuple(range(n))}
        if G is None:
            incomplete += 1; continue
        tally[len(G)] += 1
        for p in G:
            k = order_of(n, list(p))
            if k % 3 == 0:
                order3.append((idx, k, cycle_type(n, list(p))))
        if (idx + 1) % 50 == 0:
            print(f'  ... {idx+1}/{len(lines)}', flush=True)
    print(f'\n{len(lines)} graphs on {n} vertices, {incomplete} incomplete')
    print('automorphism group orders:', dict(sorted(tally.items())))
    if order3:
        print(f'\n*** {len(order3)} elements of order divisible by 3 FOUND ***')
        for idx, k, ct in order3[:10]:
            print(f'  graph {idx}: order {k}, cycle type {ct}')
    else:
        print('\nno element of order divisible by 3 in any of these graphs')
