"""Probe: how big and how hard is the orbit formula for a group of order 8?

The lane's lesson is that formula size falls with the size of the symmetry group,
and that size is what decides feasibility. If so, groups of order 8 should be
*cheaper* than order 4 -- roughly 861/8 pair orbits against 861/4 -- which would
matter, because excluding every group of order 8 bounds the Sylow 2-subgroup by 4
and so bounds the exponent a in |Aut(G)| = 2^a 3^b, which nothing does today.

Builds an action of an elementary abelian 2-group from its orbit data and reports
the pair-orbit count; solves if asked.

usage: python3 grp8probe.py
"""
import sys, os, itertools
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from groupenc import pair_orbits, clauses_for

def elem_abelian(rank):
    return [tuple(x) for x in itertools.product(range(2), repeat=rank)]

def add(u, v): return tuple((a + b) % 2 for a, b in zip(u, v))

def build_action(rank, blocks):
    """blocks: list of subgroups (as frozensets of elements) -- one orbit G/H each."""
    ELS = elem_abelian(rank)
    pts, index = [], {}
    for bi, H in enumerate(blocks):
        cosets = sorted({frozenset(add(g, h) for h in H) for g in ELS}, key=sorted)
        for C in cosets:
            index[(bi, C)] = len(pts)
            pts.append((bi, C))
    def perm(g):
        return [index[(bi, frozenset(add(g, x) for x in C))] for (bi, C) in pts]
    gens = [perm(tuple(1 if i == j else 0 for i in range(rank))) for j in range(rank)]
    return len(pts), gens

def sub(rank, gens_of_H):
    """Subgroup generated by the given elements."""
    S = {tuple([0] * rank)}
    frontier = list(S)
    while frontier:
        x = frontier.pop()
        for g in gens_of_H:
            y = add(x, g)
            if y not in S:
                S.add(y); frontier.append(y)
    return frozenset(S)

if __name__ == '__main__':
    rank = 3
    Z = tuple([0] * rank)
    triv = frozenset([Z])
    e1 = (1, 0, 0); e2 = (0, 1, 0); e3 = (0, 0, 1)
    H4 = sub(rank, [e1, e2])           # order 4 -> orbit of size 2
    H2 = sub(rank, [e1])               # order 2 -> orbit of size 4
    cases = [
        ('5 regular + one size-2 orbit', [triv] * 5 + [H4]),
        ('4 regular + two size-4 + one size-2', [triv] * 4 + [H2] * 2 + [H4]),
        ('5 regular + one size-2 (other H4)', [triv] * 5 + [sub(rank, [e2, e3])]),
    ]
    for name, blocks in cases:
        n, gens = build_action(rank, blocks)
        if n != 42:
            print(f'{name}: {n} points, skipped'); continue
        var, nv = pair_orbits(n, gens)
        cls = clauses_for(n, var)
        print(f'{name}: {n} points, {nv} pair orbits, {len(cls)} clauses')
