"""Independent standard-library checker for automorphism-restricted
(s,t,n)-Ramsey claims.

Imports nothing from encode.py.  The orbit structure is recomputed by a
different method: encode.py walks each orbit with a while-loop and numbers
orbits in discovery order, while this file computes, for every pair, the full
list of its images under the cyclic group generated by sigma, takes the
lexicographic minimum as the orbit's canonical name, and then numbers the
distinct canonical names in lexicographic order.  The two must agree.

A solver's answer is never trusted: only an LRAT refutation replayed here
counts, and only RUP steps with hints are accepted (RAT steps are rejected).

Subcommands
-----------
  lower N S T F P K FORMULA.cnf PROOF.lrat
      Certifies that no (S,T,N)-graph admits an automorphism of cycle type
      1^F P^K.  Checks that FORMULA.cnf is exactly the CNF determined by
      (N,S,T,F,P,K) and replays PROOF.lrat to the empty clause.

  cubes N S T F P K DIR D
      Certifies the type by cube-and-conquer: checks that DIR holds exactly
      the 2^D cubes over variables 1..D (every sign pattern, once), and
      replays each cube's LRAT against the base formula plus that cube.

  graph S T FILE
      Checks that an explicit graph is an (S,T,|V|)-graph: no K_S and no
      independent set of size T.  Format: first token |V|, then edge pairs.

  selftest
      Small hand-checkable cases (R(3,3)=6, R(3,4)=9, R(4,4)=18 witnesses).
"""

import itertools
import sys

# The ONLY thing this checker takes from the generator: the symF clause
# construction, which is researcher-1's (h2689) and is cited, not re-derived.
# Everything else here is regenerated independently.
from encode import symF_clauses


# ------------------------------------------------------- regenerate the CNF

def canonical_orbits(n, f, p, k):
    """pair -> orbit id, computed via explicit orbit images.

    Returns (name, nvar) where name[(u,v)] is the 0-based orbit id.
    """
    if f + p * k != n:
        raise SystemExit(f"f + p*k = {f + p*k} != n = {n}")

    def sigma(x):
        if x < f:
            return x
        j, i = divmod(x - f, p)
        return f + j * p + (i + 1) % p

    canon = {}
    for u in range(n):
        for v in range(u + 1, n):
            a, b = u, v
            images = []
            for _ in range(p if p > 0 else 1):
                images.append((a, b) if a < b else (b, a))
                a, b = sigma(a), sigma(b)
            canon[(u, v)] = min(images)
    # number the distinct canonical pairs in lexicographic order
    order = {}
    for u in range(n):
        for v in range(u + 1, n):
            c = canon[(u, v)]
            if c not in order:
                order[c] = len(order)
    return {pr: order[c] for pr, c in canon.items()}, len(order)


def regenerate(n, s, t, f, p, k, profile=False, symf=False, symc=False,
               syms=False):
    name, nvar = canonical_orbits(n, f, p, k)
    seen = set()
    order = []
    for S in itertools.combinations(range(n), s):
        cl = tuple(sorted({-(name[(u, v)] + 1)
                           for u, v in itertools.combinations(S, 2)}))
        if cl not in seen:
            seen.add(cl)
            order.append(cl)
    for T in itertools.combinations(range(n), t):
        cl = tuple(sorted({name[(u, v)] + 1
                           for u, v in itertools.combinations(T, 2)}))
        if cl not in seen:
            seen.add(cl)
            order.append(cl)
    if profile:
        idx = {pr: i for i, pr in enumerate(
            (u, w) for u in range(n) for w in range(u + 1, n))}
        orb = [0] * len(idx)
        for pr, i in idx.items():
            orb[i] = name[pr]
        order = order + [tuple(c)
                         for c in profile_clauses(n, f, p, k, idx, orb)]
    if symf:
        idx = {pr: i for i, pr in enumerate(
            (u, w) for u in range(n) for w in range(u + 1, n))}
        orb = [0] * len(idx)
        for pr, i in idx.items():
            orb[i] = name[pr]
        sf, naux = symF_clauses(n, f, p, k, idx, orb, nvar)
        order = order + [tuple(c) for c in sf]
        nvar += naux
    if symc:
        sc, naux = symC_regen(n, f, p, k, name, nvar)
        order = order + [tuple(c) for c in sc]
        nvar += naux
    if syms:
        ss, naux = symS_regen(n, f, p, k, name, nvar)
        order = order + [tuple(c) for c in ss]
        nvar += naux
    return nvar, order


def _lex_le_regen(ra, rb, aux):
    """ra <=_lex rb, written here so verify.py imports no clause builder."""
    cls = []
    prev = None
    for t, (a, b) in enumerate(zip(ra, rb)):
        cls.append(sorted((-a, b)) if prev is None else sorted((-prev, -a, b)))
        if t == len(ra) - 1:
            break
        aux += 1
        e = aux
        if prev is None:
            for c in ((-e, a, -b), (-e, -a, b), (e, a, b), (e, -a, -b)):
                cls.append(sorted(c))
        else:
            for c in ((-e, prev), (-e, a, -b), (-e, -a, b),
                      (e, -prev, a, b), (e, -prev, -a, -b)):
                cls.append(sorted(c))
        prev = e
    return cls, aux


def symC_regen(n, f, p, k, name, first_aux):
    """Rebuild symC: cycles sorted by internal code c_j = (x_{j,1..(p-1)/2})."""
    if p % 2 == 0 or k < 2:
        return [], 0
    half = (p - 1) // 2

    def internal(j, d):
        return name[(f + j * p, f + j * p + d)] + 1

    cls = []
    aux = first_aux
    for j in range(k - 1):
        ra = [internal(j, d) for d in range(1, half + 1)]
        rb = [internal(j + 1, d) for d in range(1, half + 1)]
        c, aux = _lex_le_regen(ra, rb, aux)
        cls.extend(c)
    return cls, aux - first_aux


def symS_regen(n, f, p, k, name, first_aux):
    """Rebuild the symS clauses here rather than importing them.

    What this does and does not check.  The cross rows are read off THIS
    file's own orbit naming (`canonical_orbits`, which takes a minimum over
    explicit images and shares no code with encode.pair_orbits), so a fault in
    the orbit numbering would surface as a mismatch.  The lex-CNF layout is
    the same construction written twice by the same author, so it is a
    transcription check, not an independent derivation; the mathematical
    content of symS is what `symstest.py` checks exhaustively.
    """
    if k < 2:
        return [], 0
    cls = []
    aux = first_aux
    for j in range(1, k):
        y = [name[(f, f + j * p + d)] + 1 for d in range(p)]
        for r in range(1, p):
            rot = [y[(d + r) % p] for d in range(p)]
            prev = None
            for tpos, (a, b) in enumerate(zip(rot, y)):
                cls.append(sorted((-a, b)) if prev is None
                           else sorted((-prev, -a, b)))
                if tpos == p - 1:
                    break
                aux += 1
                e = aux
                if prev is None:
                    for c in ((-e, a, -b), (-e, -a, b), (e, a, b), (e, -a, -b)):
                        cls.append(sorted(c))
                else:
                    for c in ((-e, prev), (-e, a, -b), (-e, -a, b),
                              (e, -prev, a, b), (e, -prev, -a, -b)):
                        cls.append(sorted(c))
                prev = e
    return cls, aux - first_aux


def read_dimacs(path):
    nvar = None
    out = []
    cur = []
    with open(path) as fh:
        for line in fh:
            if line[0] == "c":
                continue
            if line[0] == "p":
                nvar = int(line.split()[2])
                continue
            for tok in line.split():
                x = int(tok)
                if x == 0:
                    out.append(tuple(sorted(cur)))
                    cur = []
                else:
                    cur.append(x)
    return nvar, out


# -------------------------------------------------------------- LRAT replay

def replay(clauses, path):
    db = {i: cl for i, cl in enumerate(clauses, 1)}
    with open(path) as fh:
        for raw in fh:
            tok = raw.split()
            if not tok:
                continue
            idx = int(tok[0])
            if len(tok) > 1 and tok[1] == "d":
                for x in tok[2:]:
                    if x == "0":
                        break
                    db.pop(int(x), None)
                continue
            i = 1
            lits = []
            while tok[i] != "0":
                lits.append(int(tok[i]))
                i += 1
            i += 1
            hints = []
            while i < len(tok) and tok[i] != "0":
                h = int(tok[i])
                if h < 0:
                    raise SystemExit(f"step {idx}: RAT hint rejected "
                                     "(this checker accepts RUP only)")
                hints.append(h)
                i += 1
            val = {}
            for lit in lits:
                val[abs(lit)] = lit < 0
            conflict = False
            for h in hints:
                cl = db.get(h)
                if cl is None:
                    raise SystemExit(f"step {idx}: missing hint clause {h}")
                unit = None
                free = 0
                for lit in cl:
                    v = val.get(abs(lit))
                    if v is None:
                        free += 1
                        unit = lit
                    elif v == (lit > 0):
                        raise SystemExit(f"step {idx}: hint {h} satisfied")
                if free == 0:
                    conflict = True
                    break
                if free != 1:
                    raise SystemExit(f"step {idx}: hint {h} not unit "
                                     f"({free} free)")
                val[abs(unit)] = unit > 0
            if not conflict:
                raise SystemExit(f"step {idx}: no conflict")
            db[idx] = tuple(sorted(lits))
            if not lits:
                return idx
    raise SystemExit("proof ended without the empty clause")


# ---------------------------------------------------------------- the graph

def read_graph(path):
    tok = open(path).read().split()
    n = int(tok[0])
    e = [int(x) for x in tok[1:]]
    adj = [[False] * n for _ in range(n)]
    m = 0
    for a, b in zip(e[0::2], e[1::2]):
        if not adj[a][b]:
            m += 1
        adj[a][b] = adj[b][a] = True
    return n, adj, m


def check_graph(n, adj, s, t):
    for S in itertools.combinations(range(n), s):
        if all(adj[u][v] for u, v in itertools.combinations(S, 2)):
            return f"contains K_{s} on {S}"
    for T in itertools.combinations(range(n), t):
        if not any(adj[u][v] for u, v in itertools.combinations(T, 2)):
            return f"contains an independent {t}-set {T}"
    return None


# ------------------------------------------------------------------ command

def cmd_lower(a):
    """lower N S T F P K FORMULA.cnf PROOF.lrat [--cube l1 l2 ...]

    With --cube, the regenerated formula is the base formula plus one unit
    clause per listed literal.  A full cube split is sound because every
    total assignment satisfies exactly one cube; `cubes` below checks that
    the stored cubes are exactly all sign patterns on the split variables.
    """
    n, s, t, f, p, k = (int(x) for x in a[:6])
    nvar, want = regenerate(n, s, t, f, p, k,
                            profile="--profile" in a,
                            symf="--symf" in a,
                            symc="--symc" in a,
                            syms="--syms" in a)
    if "--cube" in a:
        for lit in a[a.index("--cube") + 1:]:
            v = int(lit)
            if not 1 <= abs(v) <= nvar:
                raise SystemExit(f"cube literal {v} out of range")
            want = want + [(v,)]
    got_nvar, got = read_dimacs(a[6])
    if got_nvar != nvar:
        raise SystemExit(f"variable count {got_nvar} != regenerated {nvar}")
    if len(got) != len(want) or set(got) != set(want):
        raise SystemExit(f"clause set differs: file {len(got)}, "
                         f"regenerated {len(want)}")
    step = replay(want, a[7])
    cube = (" under cube " + " ".join(a[a.index("--cube") + 1:])
            if "--cube" in a else "")
    print(f"VERIFIED  no ({s},{t},{n})-graph has an automorphism of cycle "
          f"type 1^{f} {p}^{k}{cube}")
    print(f"  orbit vars={nvar} clauses={len(want)} "
          f"empty clause at LRAT step {step}")


def cmd_cubes(a):
    import itertools as it
    import os
    n, s, t, f, p, k = (int(x) for x in a[:6])
    d, D = a[6], int(a[7])
    nvar, base = regenerate(n, s, t, f, p, k,
                            profile="--profile" in a,
                            symf="--symf" in a,
                            symc="--symc" in a,
                            syms="--syms" in a)
    want_cubes = {tuple((i + 1) if b else -(i + 1) for i, b in enumerate(sg))
                  for sg in it.product((True, False), repeat=D)}
    seen = set()
    for cube in sorted(want_cubes):
        tag = "c" + "".join("1" if x > 0 else "0" for x in cube)
        lrat = os.path.join(d, tag + ".lrat")
        if not os.path.exists(lrat):
            raise SystemExit(f"missing cube {tag}")
        # The cube's DIMACS need not be stored: the proof is replayed
        # directly against the formula regenerated here from
        # (n,s,t,f,p,k) plus the cube's own unit clauses.
        replay(base + [(x,) for x in cube], lrat)
        seen.add(cube)
    if seen != want_cubes:
        raise SystemExit("cube set is not exactly all sign patterns")
    print(f"VERIFIED  no ({s},{t},{n})-graph has an automorphism of cycle "
          f"type 1^{f} {p}^{k}")
    print(f"  cube-and-conquer on variables 1..{D}: all {len(seen)} cubes "
          f"present exactly once, each refuted")


def cmd_graph(a):
    s, t = int(a[0]), int(a[1])
    n, adj, m = read_graph(a[2])
    bad = check_graph(n, adj, s, t)
    if bad:
        raise SystemExit(f"NOT a ({s},{t},{n})-graph: {bad}")
    print(f"VERIFIED  ({s},{t},{n})-graph: {n} vertices, {m} edges, "
          f"no K_{s}, no independent {t}-set")


def cmd_selftest(_a):
    # C_5 is a (3,3,5)-graph; K_3-free graphs on 6 vertices always have I_3.
    c5 = [[False] * 5 for _ in range(5)]
    for i in range(5):
        c5[i][(i + 1) % 5] = c5[(i + 1) % 5][i] = True
    assert check_graph(5, c5, 3, 3) is None, "C_5 should be a (3,3,5)-graph"
    # the 8-vertex (3,4)-graph: the Wagner/Moebius-Kantor-style circulant
    # C_8(1,4) is triangle-free with independence 3.
    g = [[False] * 8 for _ in range(8)]
    for i in range(8):
        for d in (1, 4):
            g[i][(i + d) % 8] = g[(i + d) % 8][i] = True
    assert check_graph(8, g, 3, 4) is None, "C_8(1,4) should be a (3,4,8)-graph"
    # orbit agreement: identity permutation gives all-singleton orbits
    name, nv = canonical_orbits(9, 9, 1, 0)
    assert nv == 36 and len(set(name.values())) == 36
    # a full n-cycle on n=7 gives floor(7/2)=3 orbits
    name, nv = canonical_orbits(7, 0, 7, 1)
    assert nv == 3, nv
    print("selftest OK: C_5 is (3,3,5); C_8(1,4) is (3,4,8); "
          "orbit counts 36 (identity, n=9) and 3 (7-cycle)")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    {"lower": cmd_lower, "graph": cmd_graph, "cubes": cmd_cubes,
     "selftest": cmd_selftest}[sys.argv[1]](sys.argv[2:])
    return 0


if __name__ == "__main__":
    sys.exit(main())


def allowed_profile_weights(n, f, p, k):
    """Which numbers t of fully-seen cycles a fixed vertex may have.

    For a fixed vertex v, Fact 1 gives d(v) = |N(v) cap F| + p*t with
    0 <= |N(v) cap F| <= f-1, and Fact 0 gives n-25 <= d(v) <= 17 in a
    (4,6,n)-graph.  Hence p*t <= 17 and p*t >= n-24-f.

    This is the ONLY place a classical Ramsey number enters a formula:
    Fact 0 uses R(3,6) = 18 and R(4,5) = 25.  Certificates built with it
    are conditional on those two values; without --profile the encoding is
    self-contained.
    """
    return [t for t in range(k + 1) if p * t <= 17 and p * t >= n - 24 - f]


def profile_clauses(n, f, p, k, idx, orb):
    """Restrict each fixed vertex to allowed_profile_weights."""
    import itertools as _it
    ok = allowed_profile_weights(n, f, p, k)
    if not ok or (len(ok) == k + 1):
        return []
    lo, hi = min(ok), max(ok)
    if set(ok) != set(range(lo, hi + 1)):
        raise SystemExit("non-contiguous profile weights not supported")
    out = []
    for v in range(f):
        prof = [orb[idx[(v, f + j * p)]] + 1 for j in range(k)]
        for S in _it.combinations(prof, hi + 1):        # at most hi
            out.append(sorted(-x for x in S))
        if lo > 0:
            for S in _it.combinations(prof, k - lo + 1):  # at least lo
                out.append(sorted(S))
    return out
