"""Independent standard-library checker for automorphism-restricted
(s,t,n)-Ramsey claims.

Imports nothing from encode.py.  The orbit structure is recomputed by a
different method: encode.py walks each orbit with a while-loop and numbers
orbits in discovery order, while this file computes, for every pair, the full
list of its images under the cyclic group generated by sigma, takes the
lexicographic minimum as the orbit's canonical name, and then numbers the
distinct canonical names in lexicographic order.  The two must agree.

A solver's answer is never trusted: only an LRAT refutation replayed here
counts, and only RUP steps with hints are accepted (RAT steps are rejected).

Subcommands
-----------
  lower N S T F P K FORMULA.cnf PROOF.lrat
      Certifies that no (S,T,N)-graph admits an automorphism of cycle type
      1^F P^K.  Checks that FORMULA.cnf is exactly the CNF determined by
      (N,S,T,F,P,K) and replays PROOF.lrat to the empty clause.

  cubes N S T F P K DIR D
      Certifies the type by cube-and-conquer: checks that DIR holds exactly
      the 2^D cubes over variables 1..D (every sign pattern, once), and
      replays each cube's LRAT against the base formula plus that cube.

  tree N S T F P K DIR [DIR ...]
      Certifies the type by a cube split of arbitrary, non-uniform depth.
      Checks that the leaf tags form a complete prefix-free code (no tag a
      prefix of another; Kraft sum exactly 1), which is precisely the
      statement that the cubes partition the assignment space, and replays
      every leaf.

  cover DIR-or-MANIFEST [...]
      Certifies the cube-cover step itself, rather than arguing it.  Builds
      the negated-cubes formula (one clause per cube, asserting that cube is
      false), refutes it, and replays that refutation here with the same
      checker used for every leaf -- so "the cubes cover everything" carries a
      certificate instead of resting on the Kraft argument in `tree`.  If they
      do not cover, prints an explicit uncovered assignment.

  graph S T FILE
      Checks that an explicit graph is an (S,T,|V|)-graph: no K_S and no
      independent set of size T.  Format: first token |V|, then edge pairs.

  selftest
      Small hand-checkable cases (R(3,3)=6, R(3,4)=9, R(4,4)=18 witnesses).
"""

import itertools
import sys

# The ONLY thing this checker takes from the generator: the symF clause
# construction, which is researcher-1's (h2689) and is cited, not re-derived.
# Everything else here is regenerated independently.
from encode import symF_clauses


# ------------------------------------------------------- regenerate the CNF

def canonical_orbits(n, f, p, k):
    """pair -> orbit id, computed via explicit orbit images.

    Returns (name, nvar) where name[(u,v)] is the 0-based orbit id.
    """
    if f + p * k != n:
        raise SystemExit(f"f + p*k = {f + p*k} != n = {n}")

    def sigma(x):
        if x < f:
            return x
        j, i = divmod(x - f, p)
        return f + j * p + (i + 1) % p

    canon = {}
    for u in range(n):
        for v in range(u + 1, n):
            a, b = u, v
            images = []
            for _ in range(p if p > 0 else 1):
                images.append((a, b) if a < b else (b, a))
                a, b = sigma(a), sigma(b)
            canon[(u, v)] = min(images)
    # number the distinct canonical pairs in lexicographic order
    order = {}
    for u in range(n):
        for v in range(u + 1, n):
            c = canon[(u, v)]
            if c not in order:
                order[c] = len(order)
    return {pr: order[c] for pr, c in canon.items()}, len(order)


def regenerate(n, s, t, f, p, k, profile=False, symf=False, symc=False,
               syms=False):
    name, nvar = canonical_orbits(n, f, p, k)
    seen = set()
    order = []
    for S in itertools.combinations(range(n), s):
        cl = tuple(sorted({-(name[(u, v)] + 1)
                           for u, v in itertools.combinations(S, 2)}))
        if cl not in seen:
            seen.add(cl)
            order.append(cl)
    for T in itertools.combinations(range(n), t):
        cl = tuple(sorted({name[(u, v)] + 1
                           for u, v in itertools.combinations(T, 2)}))
        if cl not in seen:
            seen.add(cl)
            order.append(cl)
    if profile:
        idx = {pr: i for i, pr in enumerate(
            (u, w) for u in range(n) for w in range(u + 1, n))}
        orb = [0] * len(idx)
        for pr, i in idx.items():
            orb[i] = name[pr]
        order = order + [tuple(c)
                         for c in profile_clauses(n, f, p, k, idx, orb)]
    if symf:
        idx = {pr: i for i, pr in enumerate(
            (u, w) for u in range(n) for w in range(u + 1, n))}
        orb = [0] * len(idx)
        for pr, i in idx.items():
            orb[i] = name[pr]
        sf, naux = symF_clauses(n, f, p, k, idx, orb, nvar)
        order = order + [tuple(c) for c in sf]
        nvar += naux
    if symc:
        sc, naux = symC_regen(n, f, p, k, name, nvar)
        order = order + [tuple(c) for c in sc]
        nvar += naux
    if syms:
        ss, naux = symS_regen(n, f, p, k, name, nvar)
        order = order + [tuple(c) for c in ss]
        nvar += naux
    return nvar, order


def _lex_le_regen(ra, rb, aux):
    """ra <=_lex rb, written here so verify.py imports no clause builder."""
    cls = []
    prev = None
    for t, (a, b) in enumerate(zip(ra, rb)):
        cls.append(sorted((-a, b)) if prev is None else sorted((-prev, -a, b)))
        if t == len(ra) - 1:
            break
        aux += 1
        e = aux
        if prev is None:
            for c in ((-e, a, -b), (-e, -a, b), (e, a, b), (e, -a, -b)):
                cls.append(sorted(c))
        else:
            for c in ((-e, prev), (-e, a, -b), (-e, -a, b),
                      (e, -prev, a, b), (e, -prev, -a, -b)):
                cls.append(sorted(c))
        prev = e
    return cls, aux


def symC_regen(n, f, p, k, name, first_aux):
    """Rebuild symC: cycles sorted by internal code c_j = (x_{j,1..(p-1)/2})."""
    if p % 2 == 0 or k < 2:
        return [], 0
    half = (p - 1) // 2

    def internal(j, d):
        return name[(f + j * p, f + j * p + d)] + 1

    cls = []
    aux = first_aux
    for j in range(k - 1):
        ra = [internal(j, d) for d in range(1, half + 1)]
        rb = [internal(j + 1, d) for d in range(1, half + 1)]
        c, aux = _lex_le_regen(ra, rb, aux)
        cls.extend(c)
    return cls, aux - first_aux


def symS_regen(n, f, p, k, name, first_aux):
    """Rebuild the symS clauses here rather than importing them.

    What this does and does not check.  The cross rows are read off THIS
    file's own orbit naming (`canonical_orbits`, which takes a minimum over
    explicit images and shares no code with encode.pair_orbits), so a fault in
    the orbit numbering would surface as a mismatch.  The lex-CNF layout is
    the same construction written twice by the same author, so it is a
    transcription check, not an independent derivation; the mathematical
    content of symS is what `symstest.py` checks exhaustively.
    """
    if k < 2:
        return [], 0
    cls = []
    aux = first_aux
    for j in range(1, k):
        y = [name[(f, f + j * p + d)] + 1 for d in range(p)]
        for r in range(1, p):
            rot = [y[(d + r) % p] for d in range(p)]
            prev = None
            for tpos, (a, b) in enumerate(zip(rot, y)):
                cls.append(sorted((-a, b)) if prev is None
                           else sorted((-prev, -a, b)))
                if tpos == p - 1:
                    break
                aux += 1
                e = aux
                if prev is None:
                    for c in ((-e, a, -b), (-e, -a, b), (e, a, b), (e, -a, -b)):
                        cls.append(sorted(c))
                else:
                    for c in ((-e, prev), (-e, a, -b), (-e, -a, b),
                              (e, -prev, a, b), (e, -prev, -a, -b)):
                        cls.append(sorted(c))
                prev = e
    return cls, aux - first_aux


def read_dimacs(path):
    nvar = None
    out = []
    cur = []
    with open(path) as fh:
        for line in fh:
            if line[0] == "c":
                continue
            if line[0] == "p":
                nvar = int(line.split()[2])
                continue
            for tok in line.split():
                x = int(tok)
                if x == 0:
                    out.append(tuple(sorted(cur)))
                    cur = []
                else:
                    cur.append(x)
    return nvar, out


# -------------------------------------------------------------- LRAT replay

def replay(clauses, path):
    db = {i: cl for i, cl in enumerate(clauses, 1)}
    with open(path) as fh:
        for raw in fh:
            tok = raw.split()
            if not tok:
                continue
            idx = int(tok[0])
            if len(tok) > 1 and tok[1] == "d":
                for x in tok[2:]:
                    if x == "0":
                        break
                    db.pop(int(x), None)
                continue
            i = 1
            lits = []
            while tok[i] != "0":
                lits.append(int(tok[i]))
                i += 1
            i += 1
            hints = []
            while i < len(tok) and tok[i] != "0":
                h = int(tok[i])
                if h < 0:
                    raise SystemExit(f"step {idx}: RAT hint rejected "
                                     "(this checker accepts RUP only)")
                hints.append(h)
                i += 1
            val = {}
            for lit in lits:
                val[abs(lit)] = lit < 0
            conflict = False
            for h in hints:
                cl = db.get(h)
                if cl is None:
                    raise SystemExit(f"step {idx}: missing hint clause {h}")
                unit = None
                free = 0
                for lit in cl:
                    v = val.get(abs(lit))
                    if v is None:
                        free += 1
                        unit = lit
                    elif v == (lit > 0):
                        raise SystemExit(f"step {idx}: hint {h} satisfied")
                if free == 0:
                    conflict = True
                    break
                if free != 1:
                    raise SystemExit(f"step {idx}: hint {h} not unit "
                                     f"({free} free)")
                val[abs(unit)] = unit > 0
            if not conflict:
                raise SystemExit(f"step {idx}: no conflict")
            db[idx] = tuple(sorted(lits))
            if not lits:
                return idx
    raise SystemExit("proof ended without the empty clause")


# ---------------------------------------------------------------- the graph

def read_graph(path):
    tok = open(path).read().split()
    n = int(tok[0])
    e = [int(x) for x in tok[1:]]
    adj = [[False] * n for _ in range(n)]
    m = 0
    for a, b in zip(e[0::2], e[1::2]):
        if not adj[a][b]:
            m += 1
        adj[a][b] = adj[b][a] = True
    return n, adj, m


def check_graph(n, adj, s, t):
    for S in itertools.combinations(range(n), s):
        if all(adj[u][v] for u, v in itertools.combinations(S, 2)):
            return f"contains K_{s} on {S}"
    for T in itertools.combinations(range(n), t):
        if not any(adj[u][v] for u, v in itertools.combinations(T, 2)):
            return f"contains an independent {t}-set {T}"
    return None


# ------------------------------------------------------------------ command

def cmd_lower(a):
    """lower N S T F P K FORMULA.cnf PROOF.lrat [--cube l1 l2 ...]

    With --cube, the regenerated formula is the base formula plus one unit
    clause per listed literal.  A full cube split is sound because every
    total assignment satisfies exactly one cube; `cubes` below checks that
    the stored cubes are exactly all sign patterns on the split variables.
    """
    n, s, t, f, p, k = (int(x) for x in a[:6])
    nvar, want = regenerate(n, s, t, f, p, k,
                            profile="--profile" in a,
                            symf="--symf" in a,
                            symc="--symc" in a,
                            syms="--syms" in a)
    if "--cube" in a:
        for lit in a[a.index("--cube") + 1:]:
            v = int(lit)
            if not 1 <= abs(v) <= nvar:
                raise SystemExit(f"cube literal {v} out of range")
            want = want + [(v,)]
    got_nvar, got = read_dimacs(a[6])
    if got_nvar != nvar:
        raise SystemExit(f"variable count {got_nvar} != regenerated {nvar}")
    if len(got) != len(want) or set(got) != set(want):
        raise SystemExit(f"clause set differs: file {len(got)}, "
                         f"regenerated {len(want)}")
    step = replay(want, a[7])
    cube = (" under cube " + " ".join(a[a.index("--cube") + 1:])
            if "--cube" in a else "")
    print(f"VERIFIED  no ({s},{t},{n})-graph has an automorphism of cycle "
          f"type 1^{f} {p}^{k}{cube}")
    print(f"  orbit vars={nvar} clauses={len(want)} "
          f"empty clause at LRAT step {step}")


def cmd_cubes(a):
    import itertools as it
    import os
    n, s, t, f, p, k = (int(x) for x in a[:6])
    d, D = a[6], int(a[7])
    nvar, base = regenerate(n, s, t, f, p, k,
                            profile="--profile" in a,
                            symf="--symf" in a,
                            symc="--symc" in a,
                            syms="--syms" in a)
    want_cubes = {tuple((i + 1) if b else -(i + 1) for i, b in enumerate(sg))
                  for sg in it.product((True, False), repeat=D)}
    seen = set()
    for cube in sorted(want_cubes):
        tag = "c" + "".join("1" if x > 0 else "0" for x in cube)
        lrat = os.path.join(d, tag + ".lrat")
        if not os.path.exists(lrat):
            raise SystemExit(f"missing cube {tag}")
        # The cube's DIMACS need not be stored: the proof is replayed
        # directly against the formula regenerated here from
        # (n,s,t,f,p,k) plus the cube's own unit clauses.
        replay(base + [(x,) for x in cube], lrat)
        seen.add(cube)
    if seen != want_cubes:
        raise SystemExit("cube set is not exactly all sign patterns")
    print(f"VERIFIED  no ({s},{t},{n})-graph has an automorphism of cycle "
          f"type 1^{f} {p}^{k}")
    print(f"  cube-and-conquer on variables 1..{D}: all {len(seen)} cubes "
          f"present exactly once, each refuted")


def cmd_tree(a):
    """Verify a cube split of ARBITRARY, non-uniform depth.

    Usage: tree N S T F P K DIR [DIR ...] [flags]

    Each DIR holds files c<bits>.lrat, where <bits> is the sign pattern on
    variables 1..len(bits).  Depths may differ: a cube that closed early keeps
    its short tag, and one that did not is replaced by its children.

    SOUNDNESS.  The leaf tags must form a complete prefix-free binary code:

      * prefix-free -- no leaf tag is a prefix of another, so no assignment
        satisfies two leaves;
      * Kraft sum  sum over leaves of 2^-|tag|  equals exactly 1, so no
        assignment escapes every leaf.

    Together these say precisely that the cubes partition the space of total
    assignments, which is all the cube-and-conquer argument needs -- uniform
    depth was never required.  Each leaf is then replayed against the formula
    regenerated here plus that leaf's own unit clauses.
    """
    import os
    from fractions import Fraction
    n, s, t, f, p, k = (int(x) for x in a[:6])
    dirs = [x for x in a[6:] if not x.startswith("--")]
    nvar, base = regenerate(n, s, t, f, p, k,
                            profile="--profile" in a,
                            symf="--symf" in a,
                            symc="--symc" in a,
                            syms="--syms" in a)
    leaves = {}
    pruned = 0
    for d in dirs:
        for fn in os.listdir(d):
            if not fn.startswith("c"):
                continue
            if fn.endswith(".done"):
                # Leaf already replayed and released by prune.py; its hash is
                # in that run's manifest.  It still counts for the PARTITION
                # check, which reads only names, but it is not re-replayed
                # here and the summary says so.
                q, tag = None, fn[1:-5]
                pruned += 1
            elif fn.endswith(".lrat"):
                q = os.path.join(d, fn)
                if os.path.getsize(q) == 0:
                    continue
                tag = fn[1:-5]
            else:
                continue
            if set(tag) - set("01") or not tag:
                raise SystemExit(f"bad leaf name {fn}")
            if tag in leaves:
                raise SystemExit(f"leaf {tag} appears in two directories")
            leaves[tag] = q

    if not leaves:
        raise SystemExit("no leaves found")
    tags = sorted(leaves)
    for x, y in zip(tags, tags[1:]):          # sorted: only neighbours can nest
        if y.startswith(x):
            raise SystemExit(f"leaf {x} is a prefix of leaf {y}: not a partition")
    kraft = sum(Fraction(1, 2 ** len(x)) for x in tags)
    if kraft > 1:
        raise SystemExit(f"Kraft sum is {kraft} > 1: impossible for a "
                         f"prefix-free set; the directories overlap")

    depths = {}
    replayed = 0
    for tag, q in leaves.items():
        lits = [(i + 1) if c == "1" else -(i + 1) for i, c in enumerate(tag)]
        if q is not None:
            replay(base + [(x,) for x in lits], q)
            replayed += 1
        depths[len(tag)] = depths.get(len(tag), 0) + 1
    if kraft == 1:
        print(f"VERIFIED  no ({s},{t},{n})-graph has an automorphism of cycle "
              f"type 1^{f} {p}^{k}")
    else:
        # A prefix-free set with Kraft sum < 1 refutes exactly that fraction
        # of the assignment space and says nothing about the rest.  This is
        # reported, not treated as a failure, because partial coverage with an
        # exact measure is a real (and citable) intermediate result -- but it
        # is NOT a refutation and must never be quoted as one.
        print(f"PARTIAL   the type 1^{f} {p}^{k} is NOT refuted")
        print(f"  refuted fraction of the assignment space: {kraft} "
              f"= {float(kraft):.9f}")
        print(f"  open fraction: {1 - kraft} = {float(1 - kraft):.9f}")
    print(f"  {len(leaves)} leaves; {replayed} replayed here to the empty "
          f"clause, {pruned} replayed earlier by prune.py and released "
          f"(hashes in that run's manifest)")
    print(f"  depths: " + ", ".join(f"{d}: {c}" for d, c in sorted(depths.items())))
    if kraft == 1:
        print(f"  leaf tags are prefix-free with Kraft sum exactly 1, so they "
              f"partition all assignments")
    else:
        print(f"  leaf tags are prefix-free, so the covered fraction is exact "
              f"and the leaves do not overlap")


def collect_tags(args):
    """Leaf tags from directories of c<bits>.lrat / c<bits>.done, and/or a
    committed .jsonl.gz manifest with a "tag" field."""
    import gzip
    import json
    import os
    tags = set()
    for d in args:
        if d.startswith("--"):
            continue
        if d.endswith((".jsonl.gz", ".jsonl")):
            op = gzip.open if d.endswith(".gz") else open
            with op(d, "rt") as fh:
                for line in fh:
                    line = line.strip()
                    if line:
                        tags.add(json.loads(line)["tag"])
            continue
        for fn in os.listdir(d):
            if not fn.startswith("c"):
                continue
            if fn.endswith(".lrat"):
                if os.path.getsize(os.path.join(d, fn)) == 0:
                    continue
                tag = fn[1:-5]
            elif fn.endswith(".done"):
                tag = fn[1:-5]
            else:
                continue
            if not tag or set(tag) - set("01"):
                raise SystemExit(f"bad leaf name {fn}")
            tags.add(tag)
    if not tags:
        raise SystemExit("no leaf tags found")
    return sorted(tags)


def cmd_cover(a):
    """Certify that a set of cubes covers the assignment space, by refutation.

    Usage: cover DIR-or-MANIFEST [...] [--work W]

    WHY THIS EXISTS.  `tree` proves the cover step by checking that the leaf
    tags are prefix-free with Kraft sum exactly 1.  That argument is correct,
    but it is a hand-written combinator that no proof checker ever sees: every
    leaf carries an LRAT certificate, and then a Python function asserts that
    the leaves fit together.  The cover step is the only unchecked link in the
    chain.

    THE FIX (the construction used by LRAT-Catcher, arXiv:2607.00815, to
    assemble cube-and-conquer runs inside Lean).  Build the NEGATED-CUBES
    FORMULA: one clause per cube asserting that cube is false, i.e. the cube
    l_1 & ... & l_k contributes the clause (-l_1 v ... v -l_k).  An assignment
    satisfies this formula exactly when it falls in NO cube.  So

        negated-cubes formula unsatisfiable  <=>  the cubes cover everything,

    and that unsatisfiability is established by running the solver on it like
    any other leaf and replaying its LRAT here, with the same checker used for
    every leaf.  The trusted combinator disappears.

    TWO DIFFERENCES FROM THE KRAFT CHECK, both in this one's favour:

      * Covering is all the cube-and-conquer argument needs.  Disjointness is
        not required -- overlapping cubes are harmless, they just do work
        twice.  `tree` REJECTS a Kraft sum above 1 as "the directories
        overlap"; this accepts any genuine cover, overlapping or not.
      * When the cubes do NOT cover, the solver returns a model, which is an
        explicit uncovered assignment.  That is a concrete witness rather than
        a fraction.

    What this does NOT check: that each leaf's own refutation is valid.  That
    is `tree`'s job and remains unchanged.  The two together are the whole
    argument.
    """
    import os
    work, srcs, skip = None, [], False
    for i, x in enumerate(a):
        if skip:
            skip = False
            continue
        if x == "--work":
            work, skip = a[i + 1], True
        elif not x.startswith("--"):
            srcs.append(x)
    tags = collect_tags(srcs)
    depth = max(len(t) for t in tags)
    print(f"  {len(tags)} cubes over {depth} split variables; "
          f"negated-cubes formula: {depth} vars, {len(tags)} clauses")
    ok, info = cover_certify(tags, work)
    if not ok:
        print("NOT A COVER  the cubes leave assignments uncovered")
        print(f"  witness (an assignment in no cube): {info}")
        return
    print(f"VERIFIED  the {len(tags)} cubes cover every assignment")
    print(f"  cover certificate: {os.path.getsize(info)} bytes of LRAT, "
          f"replayed here to the empty clause")
    print("  no trusted combinator: the cover step now carries the same "
          "kind of certificate as each leaf")


def cover_certify(tags, work=None):
    """(True, lrat_path) if the cubes cover everything; (False, witness) if not.

    On the True branch the LRAT has already been verified by drat-trim AND
    replayed here to the empty clause.  On the False branch the witness is an
    explicit assignment lying in no cube.
    """
    import os
    import subprocess
    import tempfile
    depth = max(len(t) for t in tags)
    cls = [tuple(sorted(-(i + 1) if c == "1" else (i + 1)
                        for i, c in enumerate(t))) for t in tags]
    tmp = tempfile.mkdtemp(prefix="cover.") if work is None else work
    os.makedirs(tmp, exist_ok=True)
    cnf = os.path.join(tmp, "cover.cnf")
    drat = os.path.join(tmp, "cover.drat")
    lrat = os.path.join(tmp, "cover.lrat")
    with open(cnf, "w") as fh:
        fh.write(f"p cnf {depth} {len(cls)}\n")
        for c in cls:
            fh.write(" ".join(map(str, c)) + " 0\n")
    here = os.path.dirname(os.path.abspath(__file__))
    tools = os.path.join(here, "..", "..", "..", "scratch", "tools")
    cad = os.path.join(tools, "cadical", "build", "cadical")
    dtm = os.path.join(tools, "drat-trim", "drat-trim")
    r = subprocess.run([cad, "-q", "--binary=false", cnf, drat],
                       capture_output=True, text=True, check=False)
    if r.returncode == 10:
        model = sorted((int(x) for line in r.stdout.splitlines()
                        if line.startswith("v ") for x in line.split()[1:]
                        if int(x) != 0), key=abs)
        return False, "".join("1" if x > 0 else "0" for x in model)
    if r.returncode != 20:
        raise SystemExit(f"solver returned {r.returncode}, expected 10 or 20")
    v = subprocess.run([dtm, cnf, drat, "-L", lrat], capture_output=True,
                       text=True, check=False)
    if "s VERIFIED" not in v.stdout:
        raise SystemExit("drat-trim did not verify the cover proof:\n"
                         f"{v.stdout[-800:]}")
    replay(cls, lrat)                       # same checker as every leaf
    return True, lrat


def cmd_graph(a):
    s, t = int(a[0]), int(a[1])
    n, adj, m = read_graph(a[2])
    bad = check_graph(n, adj, s, t)
    if bad:
        raise SystemExit(f"NOT a ({s},{t},{n})-graph: {bad}")
    print(f"VERIFIED  ({s},{t},{n})-graph: {n} vertices, {m} edges, "
          f"no K_{s}, no independent {t}-set")


def cmd_selftest(_a):
    # C_5 is a (3,3,5)-graph; K_3-free graphs on 6 vertices always have I_3.
    c5 = [[False] * 5 for _ in range(5)]
    for i in range(5):
        c5[i][(i + 1) % 5] = c5[(i + 1) % 5][i] = True
    assert check_graph(5, c5, 3, 3) is None, "C_5 should be a (3,3,5)-graph"
    # the 8-vertex (3,4)-graph: the Wagner/Moebius-Kantor-style circulant
    # C_8(1,4) is triangle-free with independence 3.
    g = [[False] * 8 for _ in range(8)]
    for i in range(8):
        for d in (1, 4):
            g[i][(i + d) % 8] = g[(i + d) % 8][i] = True
    assert check_graph(8, g, 3, 4) is None, "C_8(1,4) should be a (3,4,8)-graph"
    # orbit agreement: identity permutation gives all-singleton orbits
    name, nv = canonical_orbits(9, 9, 1, 0)
    assert nv == 36 and len(set(name.values())) == 36
    # a full n-cycle on n=7 gives floor(7/2)=3 orbits
    name, nv = canonical_orbits(7, 0, 7, 1)
    assert nv == 3, nv
    # cover certification, on hand-checkable cube sets.  The last case is the
    # point: {0, 1, 10} covers everything but has Kraft sum 5/4, so `tree`
    # rejects it as overlapping directories while it is a perfectly good
    # cover.  Covering is what the argument needs; disjointness is not.
    for tags, want, why in (
            (["00", "01", "10", "11"], True, "uniform depth 2"),
            (["0", "10", "11"], True, "non-uniform"),
            (["0", "10"], False, "11 is uncovered"),
            (["0", "1", "10"], True, "overlapping, Kraft 5/4, still a cover"),
            (["1", "01", "00"], True, "unsorted input"),
            (["0"], False, "half the space uncovered")):
        ok, info = cover_certify(tags)
        assert ok is want, f"cover {tags} ({why}): got {ok}, wanted {want}"
        if not ok:
            assert all(not info.startswith(t) for t in tags), \
                f"cover {tags}: witness {info} is inside a cube"
    print("selftest OK: C_5 is (3,3,5); C_8(1,4) is (3,4,8); "
          "orbit counts 36 (identity, n=9) and 3 (7-cycle); "
          "6 cover cases including an overlapping cover that Kraft rejects")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    {"lower": cmd_lower, "graph": cmd_graph, "cubes": cmd_cubes,
     "tree": cmd_tree, "cover": cmd_cover,
     "selftest": cmd_selftest}[sys.argv[1]](sys.argv[2:])
    return 0


if __name__ == "__main__":
    sys.exit(main())


def allowed_profile_weights(n, f, p, k):
    """Which numbers t of fully-seen cycles a fixed vertex may have.

    For a fixed vertex v, Fact 1 gives d(v) = |N(v) cap F| + p*t with
    0 <= |N(v) cap F| <= f-1, and Fact 0 gives n-25 <= d(v) <= 17 in a
    (4,6,n)-graph.  Hence p*t <= 17 and p*t >= n-24-f.

    This is the ONLY place a classical Ramsey number enters a formula:
    Fact 0 uses R(3,6) = 18 and R(4,5) = 25.  Certificates built with it
    are conditional on those two values; without --profile the encoding is
    self-contained.
    """
    return [t for t in range(k + 1) if p * t <= 17 and p * t >= n - 24 - f]


def profile_clauses(n, f, p, k, idx, orb):
    """Restrict each fixed vertex to allowed_profile_weights."""
    import itertools as _it
    ok = allowed_profile_weights(n, f, p, k)
    if not ok or (len(ok) == k + 1):
        return []
    lo, hi = min(ok), max(ok)
    if set(ok) != set(range(lo, hi + 1)):
        raise SystemExit("non-contiguous profile weights not supported")
    out = []
    for v in range(f):
        prof = [orb[idx[(v, f + j * p)]] + 1 for j in range(k)]
        for S in _it.combinations(prof, hi + 1):        # at most hi
            out.append(sorted(-x for x in S))
        if lo > 0:
            for S in _it.combinations(prof, k - lo + 1):  # at least lo
                out.append(sorted(S))
    return out
