"""Independent standard-library checker for automorphism-restricted
(s,t,n)-Ramsey claims.

Imports nothing from encode.py.  The orbit structure is recomputed by a
different method: encode.py walks each orbit with a while-loop and numbers
orbits in discovery order, while this file computes, for every pair, the full
list of its images under the cyclic group generated by sigma, takes the
lexicographic minimum as the orbit's canonical name, and then numbers the
distinct canonical names in lexicographic order.  The two must agree.

A solver's answer is never trusted: only an LRAT refutation replayed here
counts, and only RUP steps with hints are accepted (RAT steps are rejected).

Subcommands
-----------
  lower N S T F P K FORMULA.cnf PROOF.lrat
      Certifies that no (S,T,N)-graph admits an automorphism of cycle type
      1^F P^K.  Checks that FORMULA.cnf is exactly the CNF determined by
      (N,S,T,F,P,K) and replays PROOF.lrat to the empty clause.

  cubes N S T F P K DIR D
      Certifies the type by cube-and-conquer: checks that DIR holds exactly
      the 2^D cubes over variables 1..D (every sign pattern, once), and
      replays each cube's LRAT against the base formula plus that cube.

  graph S T FILE
      Checks that an explicit graph is an (S,T,|V|)-graph: no K_S and no
      independent set of size T.  Format: first token |V|, then edge pairs.

  selftest
      Small hand-checkable cases (R(3,3)=6, R(3,4)=9, R(4,4)=18 witnesses).
"""

import itertools
import sys


# ------------------------------------------------------- regenerate the CNF

def canonical_orbits(n, f, p, k):
    """pair -> orbit id, computed via explicit orbit images.

    Returns (name, nvar) where name[(u,v)] is the 0-based orbit id.
    """
    if f + p * k != n:
        raise SystemExit(f"f + p*k = {f + p*k} != n = {n}")

    def sigma(x):
        if x < f:
            return x
        j, i = divmod(x - f, p)
        return f + j * p + (i + 1) % p

    canon = {}
    for u in range(n):
        for v in range(u + 1, n):
            a, b = u, v
            images = []
            for _ in range(p if p > 0 else 1):
                images.append((a, b) if a < b else (b, a))
                a, b = sigma(a), sigma(b)
            canon[(u, v)] = min(images)
    # number the distinct canonical pairs in lexicographic order
    order = {}
    for u in range(n):
        for v in range(u + 1, n):
            c = canon[(u, v)]
            if c not in order:
                order[c] = len(order)
    return {pr: order[c] for pr, c in canon.items()}, len(order)


def regenerate(n, s, t, f, p, k):
    name, nvar = canonical_orbits(n, f, p, k)
    seen = set()
    order = []
    for S in itertools.combinations(range(n), s):
        cl = tuple(sorted({-(name[(u, v)] + 1)
                           for u, v in itertools.combinations(S, 2)}))
        if cl not in seen:
            seen.add(cl)
            order.append(cl)
    for T in itertools.combinations(range(n), t):
        cl = tuple(sorted({name[(u, v)] + 1
                           for u, v in itertools.combinations(T, 2)}))
        if cl not in seen:
            seen.add(cl)
            order.append(cl)
    return nvar, order


def read_dimacs(path):
    nvar = None
    out = []
    cur = []
    with open(path) as fh:
        for line in fh:
            if line[0] == "c":
                continue
            if line[0] == "p":
                nvar = int(line.split()[2])
                continue
            for tok in line.split():
                x = int(tok)
                if x == 0:
                    out.append(tuple(sorted(cur)))
                    cur = []
                else:
                    cur.append(x)
    return nvar, out


# -------------------------------------------------------------- LRAT replay

def replay(clauses, path):
    db = {i: cl for i, cl in enumerate(clauses, 1)}
    with open(path) as fh:
        for raw in fh:
            tok = raw.split()
            if not tok:
                continue
            idx = int(tok[0])
            if len(tok) > 1 and tok[1] == "d":
                for x in tok[2:]:
                    if x == "0":
                        break
                    db.pop(int(x), None)
                continue
            i = 1
            lits = []
            while tok[i] != "0":
                lits.append(int(tok[i]))
                i += 1
            i += 1
            hints = []
            while i < len(tok) and tok[i] != "0":
                h = int(tok[i])
                if h < 0:
                    raise SystemExit(f"step {idx}: RAT hint rejected "
                                     "(this checker accepts RUP only)")
                hints.append(h)
                i += 1
            val = {}
            for lit in lits:
                val[abs(lit)] = lit < 0
            conflict = False
            for h in hints:
                cl = db.get(h)
                if cl is None:
                    raise SystemExit(f"step {idx}: missing hint clause {h}")
                unit = None
                free = 0
                for lit in cl:
                    v = val.get(abs(lit))
                    if v is None:
                        free += 1
                        unit = lit
                    elif v == (lit > 0):
                        raise SystemExit(f"step {idx}: hint {h} satisfied")
                if free == 0:
                    conflict = True
                    break
                if free != 1:
                    raise SystemExit(f"step {idx}: hint {h} not unit "
                                     f"({free} free)")
                val[abs(unit)] = unit > 0
            if not conflict:
                raise SystemExit(f"step {idx}: no conflict")
            db[idx] = tuple(sorted(lits))
            if not lits:
                return idx
    raise SystemExit("proof ended without the empty clause")


# ---------------------------------------------------------------- the graph

def read_graph(path):
    tok = open(path).read().split()
    n = int(tok[0])
    e = [int(x) for x in tok[1:]]
    adj = [[False] * n for _ in range(n)]
    m = 0
    for a, b in zip(e[0::2], e[1::2]):
        if not adj[a][b]:
            m += 1
        adj[a][b] = adj[b][a] = True
    return n, adj, m


def check_graph(n, adj, s, t):
    for S in itertools.combinations(range(n), s):
        if all(adj[u][v] for u, v in itertools.combinations(S, 2)):
            return f"contains K_{s} on {S}"
    for T in itertools.combinations(range(n), t):
        if not any(adj[u][v] for u, v in itertools.combinations(T, 2)):
            return f"contains an independent {t}-set {T}"
    return None


# ------------------------------------------------------------------ command

def cmd_lower(a):
    """lower N S T F P K FORMULA.cnf PROOF.lrat [--cube l1 l2 ...]

    With --cube, the regenerated formula is the base formula plus one unit
    clause per listed literal.  A full cube split is sound because every
    total assignment satisfies exactly one cube; `cubes` below checks that
    the stored cubes are exactly all sign patterns on the split variables.
    """
    n, s, t, f, p, k = (int(x) for x in a[:6])
    nvar, want = regenerate(n, s, t, f, p, k)
    if "--cube" in a:
        for lit in a[a.index("--cube") + 1:]:
            v = int(lit)
            if not 1 <= abs(v) <= nvar:
                raise SystemExit(f"cube literal {v} out of range")
            want = want + [(v,)]
    got_nvar, got = read_dimacs(a[6])
    if got_nvar != nvar:
        raise SystemExit(f"variable count {got_nvar} != regenerated {nvar}")
    if len(got) != len(want) or set(got) != set(want):
        raise SystemExit(f"clause set differs: file {len(got)}, "
                         f"regenerated {len(want)}")
    step = replay(want, a[7])
    cube = (" under cube " + " ".join(a[a.index("--cube") + 1:])
            if "--cube" in a else "")
    print(f"VERIFIED  no ({s},{t},{n})-graph has an automorphism of cycle "
          f"type 1^{f} {p}^{k}{cube}")
    print(f"  orbit vars={nvar} clauses={len(want)} "
          f"empty clause at LRAT step {step}")


def cmd_cubes(a):
    import itertools as it
    import os
    n, s, t, f, p, k = (int(x) for x in a[:6])
    d, D = a[6], int(a[7])
    nvar, base = regenerate(n, s, t, f, p, k)
    want_cubes = {tuple((i + 1) if b else -(i + 1) for i, b in enumerate(sg))
                  for sg in it.product((True, False), repeat=D)}
    seen = set()
    for cube in sorted(want_cubes):
        tag = "c" + "".join("1" if x > 0 else "0" for x in cube)
        cnf = os.path.join(d, tag + ".cnf")
        lrat = os.path.join(d, tag + ".lrat")
        if not (os.path.exists(cnf) and os.path.exists(lrat)):
            raise SystemExit(f"missing cube {tag}")
        got_nvar, got = read_dimacs(cnf)
        if got_nvar != nvar:
            raise SystemExit(f"{tag}: variable count {got_nvar} != {nvar}")
        exp = base + [(x,) for x in cube]
        if len(got) != len(exp) or set(got) != set(exp):
            raise SystemExit(f"{tag}: clause set differs from base+cube")
        replay(exp, lrat)
        seen.add(cube)
    if seen != want_cubes:
        raise SystemExit("cube set is not exactly all sign patterns")
    print(f"VERIFIED  no ({s},{t},{n})-graph has an automorphism of cycle "
          f"type 1^{f} {p}^{k}")
    print(f"  cube-and-conquer on variables 1..{D}: all {len(seen)} cubes "
          f"present exactly once, each refuted")


def cmd_graph(a):
    s, t = int(a[0]), int(a[1])
    n, adj, m = read_graph(a[2])
    bad = check_graph(n, adj, s, t)
    if bad:
        raise SystemExit(f"NOT a ({s},{t},{n})-graph: {bad}")
    print(f"VERIFIED  ({s},{t},{n})-graph: {n} vertices, {m} edges, "
          f"no K_{s}, no independent {t}-set")


def cmd_selftest(_a):
    # C_5 is a (3,3,5)-graph; K_3-free graphs on 6 vertices always have I_3.
    c5 = [[False] * 5 for _ in range(5)]
    for i in range(5):
        c5[i][(i + 1) % 5] = c5[(i + 1) % 5][i] = True
    assert check_graph(5, c5, 3, 3) is None, "C_5 should be a (3,3,5)-graph"
    # the 8-vertex (3,4)-graph: the Wagner/Moebius-Kantor-style circulant
    # C_8(1,4) is triangle-free with independence 3.
    g = [[False] * 8 for _ in range(8)]
    for i in range(8):
        for d in (1, 4):
            g[i][(i + d) % 8] = g[(i + d) % 8][i] = True
    assert check_graph(8, g, 3, 4) is None, "C_8(1,4) should be a (3,4,8)-graph"
    # orbit agreement: identity permutation gives all-singleton orbits
    name, nv = canonical_orbits(9, 9, 1, 0)
    assert nv == 36 and len(set(name.values())) == 36
    # a full n-cycle on n=7 gives floor(7/2)=3 orbits
    name, nv = canonical_orbits(7, 0, 7, 1)
    assert nv == 3, nv
    print("selftest OK: C_5 is (3,3,5); C_8(1,4) is (3,4,8); "
          "orbit counts 36 (identity, n=9) and 3 (7-cycle)")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    {"lower": cmd_lower, "graph": cmd_graph, "cubes": cmd_cubes,
     "selftest": cmd_selftest}[sys.argv[1]](sys.argv[2:])
    return 0


if __name__ == "__main__":
    sys.exit(main())
