r"""reviewer-1: the composition matrix of h3295, checked with my own code.

For a set of breakers, a combination is SOUND if every orbit of the symmetry
group retains at least one member satisfying all of them at once; the count
reported here is the number of assignments lying in orbits that retain none
("uncovered"), so 0 means sound and anything else exhibits the failure.

The group is generated by the shifts \(\Phi_b\), the multipliers \(\mu_u\), the
cycle permutations \(\Phi_\tau\) and, when \(f > 0\), the permutations of the
fixed-point set — all read off vertex permutations by my own code.  The
predicates are my own, written from the prose in the lane's `encode.py`:

  symS  each \(y^{(j)}\), j = 1..k-1, is the lex-greatest of its p rotations
  symC  internal codes sorted, c_0 <=_lex ... <=_lex c_{k-1}
  symK  lex-greatest under all cycle permutations
  symM  lex-greatest under all multipliers
  symF  R_u <=_lex R_{u+1} for u = 0..f-2, the rows of h2689
"""
import itertools

from indep_syms import (orbits, phi_shift, phi_cycle, mu_mult, induced, act,
                        sym_s, sym_c, internal_code)


def perm_fixed(f, p, k, rho):
    n = f + p * k
    pi = list(range(n))
    for u in range(f):
        pi[u] = rho[u]
    return pi


def group(f, p, k, oid, norb):
    gens = [phi_shift(f, p, k, b) for b in itertools.product(range(p), repeat=k)]
    gens += [mu_mult(f, p, k, u) for u in range(1, p)]
    gens += [phi_cycle(f, p, k, tau) for tau in itertools.permutations(range(k))]
    if f > 1:
        gens += [perm_fixed(f, p, k, rho)
                 for rho in itertools.permutations(range(f))]
    maps = []
    for pi in gens:
        g = induced(pi, oid, norb)
        if g is None:
            raise SystemExit('generator is not well defined on orbits')
        maps.append(tuple(g))
    ident = tuple(range(norb))
    seen, frontier = {ident}, [ident]
    while frontier:
        cur = frontier.pop()
        for g in maps:
            nxt = tuple(g[cur[o]] for o in range(norb))
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return sorted(seen)


def sym_k(f, p, k, oid, norb, x, maps):
    return all(list(act(g, x)) <= list(x) for g in maps)


def make_maps(f, p, k, oid, norb, which):
    if which == 'cycles':
        gens = [phi_cycle(f, p, k, tau)
                for tau in itertools.permutations(range(k))]
    else:
        gens = [mu_mult(f, p, k, u) for u in range(1, p)]
    return [tuple(induced(pi, oid, norb)) for pi in gens]


def sym_f(f, p, k, oid, x):
    if f < 2:
        return True
    def var(a, b):
        return x[oid[(min(a, b), max(a, b))]]
    for u in range(f - 1):
        others = [w for w in range(f) if w != u and w != u + 1]
        ra = [var(u, f + j * p) for j in range(k)] + [var(u, w) for w in others]
        rb = [var(u + 1, f + j * p) for j in range(k)] + \
             [var(u + 1, w) for w in others]
        if ra > rb:
            return False
    return True


COMBOS = [('symS',), ('symC',), ('symK',), ('symM',), ('symF',),
          ('symS', 'symC'), ('symS', 'symF'), ('symS', 'symC', 'symF'),
          ('symS', 'symM'), ('symS', 'symK'), ('symK', 'symM'),
          ('symC', 'symM'), ('symC', 'symF'), ('symC', 'symK')]


def run(f, p, k):
    oid, norb = orbits(f, p, k)
    G = group(f, p, k, oid, norb)
    kmaps = make_maps(f, p, k, oid, norb, 'cycles')
    mmaps = make_maps(f, p, k, oid, norb, 'mult')
    assignments = list(itertools.product((0, 1), repeat=norb))

    def holds(name, x):
        if name == 'symS':
            return sym_s(f, p, k, oid, x)
        if name == 'symC':
            return p % 2 == 1 and sym_c(f, p, k, oid, x)
        if name == 'symK':
            return sym_k(f, p, k, oid, norb, x, kmaps)
        if name == 'symM':
            return sym_k(f, p, k, oid, norb, x, mmaps)
        if name == 'symF':
            return sym_f(f, p, k, oid, x)
        raise KeyError(name)

    print(f'f={f} p={p} k={k}: {norb} orbit variables, {len(assignments)} '
          f'assignments, symmetry group of order {len(G)}', flush=True)
    # orbit partition
    seen = {}
    orbs = []
    for x in assignments:
        if x in seen:
            continue
        cls = {act(g, x) for g in G}
        i = len(orbs)
        orbs.append(sorted(cls))
        for y in cls:
            seen[y] = i
    print(f'  {len(orbs)} orbits under the group', flush=True)
    for combo in COMBOS:
        if 'symC' in combo and p % 2 == 0:
            continue
        if 'symF' in combo and f < 2:
            continue
        keep = {x for x in assignments if all(holds(nm, x) for nm in combo)}
        uncovered = sum(len(o) for o in orbs if not any(y in keep for y in o))
        lost = sum(1 for o in orbs if not any(y in keep for y in o))
        tag = 'SOUND' if lost == 0 else '*** UNSOUND ***'
        print(f'  {"+".join(combo):22s} survivors {len(keep):6d}  '
              f'orbits with no survivor {lost:5d}  assignments uncovered '
              f'{uncovered:6d}  {tag}', flush=True)


if __name__ == '__main__':
    for case in [(0, 3, 2), (0, 5, 2), (0, 7, 2), (0, 3, 3), (2, 3, 2)]:
        run(*case)
        print(flush=True)
