"""Independent checker for the cube-and-conquer refutation of cycle type 1^0 7^6
(a (5,5,42)-graph with a fixed-point-free automorphism of order 7).

Certificate = (cubes.icnf, basesym.cnf, certificates c<i>.lrat.xz, manifest).
This script (standard library only) checks, with code written separately
from the generators:
  1. the DIMACS file basesym.cnf is exactly the orbit formula of type 7^6
     (regenerated by verify.build) plus the symmetry-breaking clauses S
     (regenerated here from their definition; see README, "Free cycles");
  2. every cube fixes exactly the orbit variables of the first K cycles
     (3 internal + 7 per pair), and, decoded as a Z_7-graph on K cycles, it is
     (5,5)-good and equal to its own canonical form under the full equivariant
     group (complement x multiplier x S_K x rotations), computed by brute force;
  3. (K = 2 only, --complete) the cube set equals the set of canonical forms of
     ALL 6*6*128 labelled (5,5)-good 2-cycle graphs, by brute force;
  4. every certificate c<i>.lrat.xz has the SHA-256 recorded in the manifest and
     is a valid RUP-only LRAT refutation of basesym.cnf + the unit clauses of
     cube i (clause ids: file order, then the cube literals in cube order).
usage: python3 verify_cnc.py cubes.icnf basesym.cnf certdir manifest.json [K] [--complete] [--jobs N] [--only i,j,...] [--skip-canon]
Exit status 0 iff everything checked passed. Certificates missing from certdir are
reported (their hashes are in the manifest) and counted as unchecked, not failed."""
import sys, os, json, itertools, lzma, hashlib
from multiprocessing import Pool
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from verify import build, read_dimacs, check_lrat

N, P, K6 = 42, 7, 6
FULL = 127

def pair_vars():
    """orbit variables of type 7^6 on 42 vertices: orbit of a pair = its images under
    the cyclic shift on every cycle; orbits numbered by lexicographically least pair."""
    sig = {P * j + i: P * j + (i + 1) % P for j in range(K6) for i in range(P)}
    least = {}
    for u, v in itertools.combinations(range(N), 2):
        a, b = u, v; orb = []
        for _ in range(P):
            orb.append((a, b) if a < b else (b, a)); a, b = sig[a], sig[b]
        least[(u, v)] = min(orb)
    reps = sorted(set(least.values()))
    num = {r: i + 1 for i, r in enumerate(reps)}
    return {e: num[r] for e, r in least.items()}

def val(W):  # 7-bit word as an integer, bit 0 (residue 0) most significant
    return int(''.join('1' if W >> r & 1 else '0' for r in range(P)), 2)
def rot(W, t): return sum(1 << ((r + t) % P) for r in range(P) if W >> r & 1)
def mul(W, u): return sum(1 << ((r * u) % P) for r in range(P) if W >> r & 1)

def sym_clauses(var, free):
    """S: for each free cycle j the word W_0j (bit r <-> pair (0, 7j+r)) is the least
    of its 7 rotations; for consecutive free cycles j < l, val(W_0j) <= val(W_0l)."""
    minimal = [W for W in range(128) if all(val(W) <= val(rot(W, t)) for t in range(P))]
    wv = {j: [var[(0, P * j + r)] for r in range(P)] for j in free}
    forbid = lambda vs, W: [-v if W >> r & 1 else v for r, v in enumerate(vs)]
    out = []
    for j in free:
        out += [forbid(wv[j], W) for W in range(128) if W not in minimal]
    for j, l in zip(free, free[1:]):
        out += [forbid(wv[j], A) + forbid(wv[l], B) for A in minimal for B in minimal if val(A) > val(B)]
    return out

# ---- Z_7-graphs on K cycles: decode, goodness, brute-force canonical form ----
def decode(cube, var, K):
    """cube literals -> (codes, words); codes[j] = set of internal distances in {1,2,3}."""
    inv = {}
    for e in sorted(var): inv.setdefault(var[e], e)   # variable -> least pair of its orbit
    assign = {}
    for l in cube:
        e = inv[abs(l)]; assert e not in assign, 'duplicate variable in cube'
        assign[e] = l > 0
    want = {(P * j, P * j + d) for j in range(K) for d in (1, 2, 3)} | {(P * j, P * l + r) for j in range(K) for l in range(j + 1, K) for r in range(P)}
    assert set(assign) == want, 'cube does not fix exactly the first K cycles'
    codes = [frozenset(d for d in (1, 2, 3) if assign[(P * j, P * j + d)]) for j in range(K)]
    words = {(j, l): sum(1 << r for r in range(P) if assign[(P * j, P * l + r)]) for j in range(K) for l in range(j + 1, K)}
    return codes, words

def adjacency(codes, words):
    K = len(codes); adj = [0] * (P * K)
    for j, s in enumerate(codes):
        for i in range(P):
            for d in s:
                adj[P * j + i] |= 1 << (P * j + (i + d) % P) | 1 << (P * j + (i - d) % P)
    for (j, l), W in words.items():
        for i in range(P):
            for r in range(P):
                if W >> r & 1:
                    a, b = P * j + i, P * l + (i + r) % P
                    adj[a] |= 1 << b; adj[b] |= 1 << a
    return adj

def clique(adj, cand, size):
    """does the vertex set `cand` (bitmask) contain a clique of `size` vertices of adj?"""
    if size == 0: return True
    while cand:
        v = cand.bit_length() - 1; cand &= ~(1 << v)
        if clique(adj, cand & adj[v], size - 1): return True
    return False

def good(adj):
    """(5,5)-good: no K5 and no independent 5-set (all 5-sets, via clique search)."""
    n = len(adj); allv = (1 << n) - 1
    cadj = [allv & ~adj[v] & ~(1 << v) for v in range(n)]
    return not clique(adj, allv, 5) and not clique(cadj, allv, 5)

def key_of(codes, words):
    K = len(codes)
    return (tuple(sum(1 << (d - 1) for d in s) for s in codes), tuple(words[(a, b)] for b in range(1, K) for a in range(b)))

def transform(codes, words, c, u, perm, ts):
    K = len(codes)
    cd = [frozenset((d * u) % P if (d * u) % P <= 3 else P - (d * u) % P for d in s) for s in codes]
    wd = {jl: mul(W, u) for jl, W in words.items()}
    if c:
        cd = [frozenset({1, 2, 3}) - s for s in cd]; wd = {jl: FULL ^ W for jl, W in wd.items()}
    ncodes = [cd[perm[a]] for a in range(K)]; nwords = {}
    for b in range(1, K):
        for a in range(b):
            ja, jb = perm[a], perm[b]
            W = wd[(ja, jb)] if ja < jb else mul(wd[(jb, ja)], P - 1)
            nwords[(a, b)] = rot(W, ts[b] - ts[a])
    return ncodes, nwords

def brute_canon(codes, words):
    K = len(codes); best = None
    for c in (0, 1):
        for u in range(1, P):
            for perm in itertools.permutations(range(K)):
                for ts in itertools.product(range(P), repeat=K - 1):
                    k = key_of(*transform(codes, words, c, u, perm, (0,) + ts))
                    if best is None or k < best: best = k
    return best

# ---- per-cube certificate check (worker) ----
_G = {}
def _init(cls, certdir, manifest):
    _G['cls'] = cls; _G['certdir'] = certdir; _G['manifest'] = manifest
def sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as fh:
        for b in iter(lambda: fh.read(1 << 20), b''): h.update(b)
    return h.hexdigest()
def check_cube(args):
    i, cube = args
    path = os.path.join(_G['certdir'], f'c{i}.lrat.xz')
    if not os.path.exists(path): return i, 'missing'
    rec = _G['manifest'][str(i)]
    if rec['cube'] != cube: return i, 'manifest cube mismatch'
    if sha256(path) != rec['sha256']: return i, 'sha256 mismatch'
    try:
        ok = check_lrat(_G['cls'] + [[l] for l in cube], path)
    except Exception as e:
        return i, f'LRAT error: {e}'
    return i, 'VERIFIED' if ok else 'no empty clause'

def main():
    argv = sys.argv[1:]; jobs = 4; only = None
    if '--jobs' in argv:
        i = argv.index('--jobs'); jobs = int(argv[i + 1]); del argv[i:i + 2]
    if '--only' in argv:
        i = argv.index('--only'); only = set(map(int, argv[i + 1].split(','))); del argv[i:i + 2]
    args = [a for a in argv if not a.startswith('--')]
    icnf, cnfpath, certdir, manpath = args[:4]
    K = int(args[4]) if len(args) > 4 else 3
    var = pair_vars()
    # 1. formula
    nv, base = build(N, 0, P, K6)
    S = sym_clauses(var, tuple(range(K, K6)))
    nv2, cls = read_dimacs(cnfpath)
    canon_c = lambda c: tuple(sorted(c, key=lambda x: (abs(x), x)))
    got = [canon_c(c) for c in cls]
    baseset = {canon_c(c) for c in base}; symset = {canon_c(c) for c in S}
    want = baseset | symset
    assert nv == nv2 == 123, (nv, nv2)
    assert len(got) == len(set(got)) == len(want) == len(base) + len(S) and set(got) == want, 'formula mismatch'
    assert all(c in baseset for c in got[:len(base)]), 'base clauses must come first'
    print(f'formula: {len(base)} orbit clauses + {len(S)} symmetry clauses, 123 variables, matches basesym.cnf (sha256 {sha256(cnfpath)})')
    # 2. cubes
    cubes = [list(map(int, l.split()[1:-1])) for l in open(icnf) if l.startswith('a ')]
    keys = set(); bad = 0
    for i, cube in enumerate(cubes):
        codes, words = decode(cube, var, K)
        if not good(adjacency(codes, words)): print(f'cube {i}: not (5,5)-good'); bad += 1
        k = key_of(codes, words)
        if '--skip-canon' not in sys.argv and brute_canon(codes, words) != k: print(f'cube {i}: not canonical'); bad += 1
        keys.add(k)
    assert len(keys) == len(cubes), 'duplicate cubes'
    print(f'cubes: {len(cubes)} distinct canonical (5,5)-good Z_7-graphs on {K} cycles ({bad} failures)')
    # 3. completeness (K = 2, exact)
    if '--complete' in sys.argv:
        assert K == 2, 'exact completeness check implemented for K = 2 only'
        allk = set()
        for s in range(1, 7):
            for t in range(1, 7):
                for W in range(128):
                    codes = [frozenset(d for d in (1, 2, 3) if s >> (d - 1) & 1), frozenset(d for d in (1, 2, 3) if t >> (d - 1) & 1)]
                    words = {(0, 1): W}
                    if good(adjacency(codes, words)): allk.add(brute_canon(codes, words))
        assert allk == keys, f'completeness failure: {len(allk)} canonical forms vs {len(keys)} cubes'
        print(f'completeness: canonical forms of all labelled (5,5)-good 2-cycle graphs == cube set ({len(allk)})')
    # 4. certificates
    if manpath == 'none':
        print('RESULT:', 'all checks passed (no certificates checked)' if bad == 0 else 'FAILURES'); sys.exit(0 if bad == 0 else 1)
    manifest = json.load(open(manpath))
    todo = [(i, c) for i, c in enumerate(cubes) if only is None or i in only]
    counts = {}
    with Pool(jobs, initializer=_init, initargs=(cls, certdir, manifest)) as pool:
        for i, res in pool.imap_unordered(check_cube, todo, chunksize=4):
            counts[res] = counts.get(res, 0) + 1
            if res not in ('VERIFIED', 'missing'): print(f'cube {i}: {res}')
    print('certificates:', ', '.join(f'{v} {k}' for k, v in sorted(counts.items())))
    ok = bad == 0 and all(k in ('VERIFIED', 'missing') for k in counts)
    print('RESULT:', 'all checks passed' if ok else 'FAILURES')
    sys.exit(0 if ok else 1)

if __name__ == '__main__':
    main()
