"""Orderly generation of canonical (5,5)-good Z_p-graphs on k cycles, with a
canonical form that does not enumerate the whole equivariant group.

A Z_p-graph on k cycles is (codes, words): codes[j] is the internal distance set
of cycle j (for p = 3 either the triangle or the empty triple), and words[(j,l)]
for j < l is the p-bit set of residues r with (j,i) ~ (l,i+r).

The equivariant group is generated by complementation, the multipliers
u in Z_p^*, the permutations of the cycles, and the rotations of each cycle:
its order is 2 (p-1) k! p^k, which is 38880 already for p = 3, k = 5, so the
brute-force canonical form of zpenum.py becomes the bottleneck. Here the
canonical form is computed as
  min over (complement, multiplier, choice of the cycle that becomes cycle 0,
            rotation of that cycle)                                (2 (p-1) k p options)
of a key built greedily: every other cycle's rotation is chosen to minimise its
word to cycle 0 (all p rotations are tried when that word is rotation-invariant),
the other cycles are then sorted by (code, word to cycle 0), and ties between
cycles with equal sort keys are resolved by trying the permutations inside each
tied block. That is exact -- it minimises over the same group -- but touches only
a small part of it.

usage: python3 zpenum_fast.py K [P]      writes level{K}_p{P}.json, prints counts
       python3 zpenum_fast.py --check    checks the canonical form against
                                         zpenum.canon on random small inputs
"""
import sys, json, itertools, time

P = int(sys.argv[2]) if len(sys.argv) > 2 and not sys.argv[1].startswith('--') else 3
H = (P - 1) // 2
CFULL = (1 << H) - 1
CODES = [0, 1] if P == 3 else [s for s in range(1 << H) if s not in (0, CFULL)]
FULL = (1 << P) - 1

def code_adj(s):
    return {d for d in range(1, H + 1) if s >> (d - 1) & 1} | {P - d for d in range(1, H + 1) if s >> (d - 1) & 1}
def rot(W, t): return sum(1 << ((r + t) % P) for r in range(P) if W >> r & 1)
def mul(W, u): return sum(1 << ((r * u) % P) for r in range(P) if W >> r & 1)
def neg(W): return mul(W, P - 1)
def code_mul(s, u):
    A = {(a * u) % P for a in code_adj(s)}
    return sum(1 << (d - 1) for d in range(1, H + 1) if d in A)

def build(codes, words):
    k = len(codes); n = P * k; adj = [0] * n
    for j, s in enumerate(codes):
        for i in range(P):
            for r in code_adj(s): adj[P * j + i] |= 1 << (P * j + (i + r) % P)
    for (j, l), W in words.items():
        for i in range(P):
            for r in range(P):
                if W >> r & 1:
                    a, b = P * j + i, P * l + (i + r) % P
                    adj[a] |= 1 << b; adj[b] |= 1 << a
    return adj

def popcount(x): return bin(x).count('1')
def has_clique(adj, cand, size):
    if size == 0: return True
    if popcount(cand) < size: return False
    if size == 1: return cand != 0
    while cand:
        v = cand & -cand; vi = v.bit_length() - 1
        cand ^= v
        if has_clique(adj, cand & adj[vi], size - 1): return True
        if popcount(cand) < size: return False
    return False

def good_new_cycle(adj, k):
    """(5,5)-goodness of the 5-sets through the first vertex of the last cycle,
    assuming the first k-1 cycles are already good (Z_p symmetry does the rest)."""
    n = P * k; v0 = P * (k - 1); allv = (1 << n) - 1
    N = adj[v0]; Nc = allv & ~N & ~(1 << v0)
    if has_clique(adj, N, 4): return False
    cadj = [allv & ~a & ~(1 << i) for i, a in enumerate(adj)]
    return not has_clique(cadj, Nc, 4)

def transform(codes, words, c, u):
    """complement and multiplier, before any relabelling."""
    cd = [code_mul(s, u) for s in codes]
    wd = {jl: mul(W, u) for jl, W in words.items()}
    if c:
        cd = [CFULL - s for s in cd]; wd = {jl: FULL ^ W for jl, W in wd.items()}
    return cd, wd

def word(wd, a, b):
    return wd[(a, b)] if a < b else neg(wd[(b, a)])

def key_from(cd, wd, order, rots):
    """key of the labelling: cycle order[a] becomes a, rotated by rots[a]."""
    k = len(order)
    codes = tuple(cd[order[a]] for a in range(k))
    ws = []
    for b in range(1, k):
        for a in range(b):
            ws.append(rot(word(wd, order[a], order[b]), rots[b] - rots[a]))
    return (codes, tuple(ws))

def canon(codes, words):
    """canonical (least) key over the equivariant group."""
    k = len(codes); best = None
    for c in (0, 1):
        for u in range(1, P):
            cd, wd = transform(codes, words, c, u)
            for first in range(k):
                for t0 in range(P):
                    # rotations of the other cycles: minimise the word to the first cycle
                    opts = []
                    for j in range(k):
                        if j == first: continue
                        W = rot(word(wd, first, j), -t0)
                        cand = sorted(range(P), key=lambda t: rot(W, t))
                        least = rot(W, cand[0])
                        ts = [t for t in range(P) if rot(W, t) == least]
                        opts.append((j, least, ts))
                    # sort the other cycles by (code, least word); resolve ties by permuting blocks
                    opts.sort(key=lambda o: (cd[o[0]], o[1]))
                    groups = []
                    i = 0
                    while i < len(opts):
                        j = i + 1
                        while j < len(opts) and (cd[opts[j][0]], opts[j][1]) == (cd[opts[i][0]], opts[i][1]): j += 1
                        groups.append(opts[i:j]); i = j
                    for perm in itertools.product(*[itertools.permutations(g) for g in groups]):
                        flat = [o for g in perm for o in g]
                        for rots_rest in itertools.product(*[o[2] for o in flat]):
                            order = [first] + [o[0] for o in flat]
                            rots = [t0] + list(rots_rest)
                            key = key_from(cd, wd, order, rots)
                            if best is None or key < best: best = key
    return best

def unkey(key):
    codes, wl = key; k = len(codes); words = {}; idx = 0
    for b in range(1, k):
        for a in range(b): words[(a, b)] = wl[idx]; idx += 1
    return list(codes), words

def pair_allowed():
    allowed = {}
    for s in CODES:
        for t in CODES:
            ok = [W for W in range(FULL + 1) if good_new_cycle(build([s, t], {(0, 1): W}), 2)]
            allowed[(s, t)] = ok
    return allowed

def main():
    K = int(sys.argv[1]); t0 = time.time()
    allowed = pair_allowed()
    reps = {canon([s], {}) for s in CODES}
    print(f'level 1: {len(reps)} reps', flush=True)
    for k in range(2, K + 1):
        new = set(); tried = 0
        for key in sorted(reps):
            codes, words = unkey(key)
            for s in CODES:
                lists = [allowed[(codes[j], s)] for j in range(k - 1)]
                for ws in itertools.product(*lists):
                    tried += 1
                    words2 = dict(words)
                    for j in range(k - 1): words2[(j, k - 1)] = ws[j]
                    adj = build(codes + [s], words2)
                    if not good_new_cycle(adj, k): continue
                    new.add(canon(codes + [s], words2))
        reps = new
        print(f'level {k}: {len(reps)} reps ({tried} candidates, {time.time() - t0:.0f} s)', flush=True)
        json.dump(sorted(reps), open(f'level{k}_p{P}.json', 'w'))

def check():
    """compare with the brute-force canonical form of zpenum.py on random inputs."""
    import random
    sys.argv = ['zpenum.py', '3', str(P)]
    import zpenum
    random.seed(3); bad = 0
    for trial in range(300):
        k = random.choice([2, 3])
        codes = [random.choice(CODES) for _ in range(k)]
        words = {(a, b): random.randrange(FULL + 1) for b in range(1, k) for a in range(b)}
        if canon(codes, words) != zpenum.canon(codes, words):
            bad += 1
            if bad < 3: print('MISMATCH', codes, words, canon(codes, words), zpenum.canon(codes, words))
    print(f'canonical form agrees with zpenum.canon on {300 - bad} of 300 random inputs')

if __name__ == '__main__':
    check() if sys.argv[1] == '--check' else main()
